### ISSUE TITLE
Report seed for failed Proptest tests in CI

### ISSUE THREAD

**Issue by shekhirin** [paradigmxyz/reth#10610]
### Describe the feature

If `proptest` fails, we have no insight into how to reproduce the failure. We should report the seed used for the test run.

I'm sure there's a native way to do so in `proptest-rs`.

**Comment by greged93** [comment]
hey @shekhirin I'm down to work on this

**Comment by greged93** [comment]
looking into `proptest` a little, it seems it will by default report the seed in `stdout` and create a `proptest-regressions` with this failing seed.

It is then recommended to commit this file in order to avoid regression. We could have the CI create a PR on failing proptests to merge the `proptest-regresssions` file but might be a little much. Let me know where you want to go with this @shekhirin.

- https://proptest-rs.github.io/proptest/proptest/failure-persistence.html

**Comment by shekhirin** [comment]
@greged93 here's a failure that we recently had https://github.com/paradigmxyz/reth/actions/runs/10615954550/job/29425196986

Now that I look deeper into it, I think it's not a proptest failure, but just a benchmark failing due to bad test vectors that were generated with proptest https://github.com/paradigmxyz/reth/blob/e1a701204d76b3e151d512f5eedd8c678a3fa9b4/crates/cli/commands/src/test_vectors/tables.rs#L82-L83

What we should do is to print to stdout the seed that was used to generate test vectors, so we can reproduce the error in benchmarks locally.

**Comment by greged93** [comment]
ah got it, will look into getting the seed out of benchmarks
