### ISSUE TITLE
Support multiple all eth protocol versions announced in HelloMessage

### ISSUE THREAD

**Issue by mattsse** [paradigmxyz/reth#1101]
### Describe the feature

as highlighted here:
https://t.me/paradigm_reth/1611

we're announcing support for eth66/67 by default in `Hello` but only check for a single version in the eth `Status` handshake.

https://github.com/paradigmxyz/reth/blob/e0dbcaece34839745801606716478773a74170fa/crates/net/eth-wire/src/ethstream.rs#L101-L106

the status message should also accept older versions if announced.

## TODO
if we add this to `Status` directly, we can no longer derive Rlp 
so perhaps we add a list of versions as a separate parameter to the `handshake` function

wdyt @Rjected

**Comment by Rjected** [comment]
I think this is because we always use `EthVersion::Eth67` in the `Default` impl of `Status`:
https://github.com/paradigmxyz/reth/blob/e0dbcaece34839745801606716478773a74170fa/crates/net/eth-wire/src/types/status.rs#L152-L158

Instead, this should be selected depending on the highest version shared `eth` capability. Ideally this would be fully solved by #791 in a way that lets us preserve the current behavior, but for now, adding a parameter in `handshake` seems like the best solution

**Comment by mattsse** [comment]
> Instead, this should be selected depending on the highest version shared eth capability.

for the handshake this should check that the version of the remote peer's Status message is supported.

**Comment by Rjected** [comment]
> for the handshake this should check that the version of the remote peer's Status message is supported.

right, yeah

**Comment by gakonst** [comment]
A few questions:
1. Does Geth announce support for multiple protocol versions too? Looks like [yes](https://github.com/ethereum/go-ethereum/blob/d0a4989a8def7e6bad182d1513e8d4a093c1672d/eth/protocols/eth/protocol.go#L44), incl [eth/68](https://github.com/ethereum/go-ethereum/pull/25980).
2. Their [`handshake`](https://github.com/ethereum/go-ethereum/blob/d0a4989a8def7e6bad182d1513e8d4a093c1672d/eth/protocols/eth/handshake.go#L36-L45) does not seem to take a protocol version, but the peer does have a [negotiated version](https://github.com/ethereum/go-ethereum/blob/d0a4989a8def7e6bad182d1513e8d4a093c1672d/eth/protocols/eth/peer.go#L97-L102)
3. And it seems like they try to do a handshake for [each version](https://github.com/ethereum/go-ethereum/blob/d0a4989a8def7e6bad182d1513e8d4a093c1672d/eth/protocols/eth/handler.go#L97-L107)


So is the idea that since we don't support multiple protocols yet, we'd just "loosen" the check from "if our version is not the same as theirs" to "if our version is eth/67 and their version is eth/66 or eth/67 we still mark it as an OK handshake"?

**Comment by Rjected** [comment]
> So is the idea that since we don't support multiple protocols yet, we'd just "loosen" the check from "if our version is not the same as theirs" to "if our version is eth/67 and their version is eth/66 or eth/67 we still mark it as an OK handshake"?

yes, that's the short term fix, and the long term fix is supporting multiple protocol versions, which will look a lot like how geth does it.

**Comment by gakonst** [comment]
But should we be announcing eth/66? We're not responding to GetNodeData for example, so won't that get us penalized? 

Should we just not advertise support for eth/66, and properly do the multiple caps? Most of the network is on latest geth anyway, so they all have eth/67, I doubt that we'd lose a lot of peers that way?

**Comment by Rjected** [comment]
> Should we just not advertise support for eth/66, and properly do the multiple caps? Most of the network is on latest geth anyway, so they all have eth/67, I doubt that we'd lose a lot of peers that way?

After some research, I'm leaning much more toward implementing support for multiple protocol versions, and don't think peers with `eth/66`, but _not_ `eth/67` are a significant share of the network. Looking at [ethernodes](https://ethernodes.org/client/geth), the most used version of geth is [1.10.25](https://github.com/ethereum/go-ethereum/releases/tag/v1.10.25). The only older version with significant network share, [1.10.23](https://github.com/ethereum/go-ethereum/releases/tag/v1.10.23), is at about 6%.

`eth/67` was implemented in https://github.com/ethereum/go-ethereum/pull/24093, around June of 2022, for [1.10.19](https://github.com/ethereum/go-ethereum/releases/tag/v1.10.19). The PR even notes the following:
>  (3) OpenEthereum and Erigon stopped serving fast sync data already even at the expense of a protocol violation, eth67 is just catching up with the general direction

So most nodes should support `eth/67`

**Comment by gakonst** [comment]
Yeah, so I think let's just stop advertising eth/66, and when we can prioritize, go for the multiple caps?

**Comment by jinsankim** [comment]
Need feedback.

Alternative idea to original issue, passing `a list of versions` to `handshake`:
* Could we overwrite `SharedCapability::Eth.version`, from `UnauthedP2PStream.handshake()`, to status.version?

Rationale to my alternative idea:
* `geth` negotiates `eth` protocol and it selects `highest` version.
https://github.com/ethereum/go-ethereum/blob/d0a4989a8def7e6bad182d1513e8d4a093c1672d/cmd/devp2p/internal/ethtest/helpers.go#L130-L132
* We also already have the same logic at
https://github.com/paradigmxyz/reth/blob/a55e7fd9b5b40acce3030a9366285947455138be/crates/net/eth-wire/src/p2pstream.rs#L562-L567

HDYT?
