### ISSUE TITLE
Extend EthApi with execution helpers

### ISSUE THREAD

**Issue by mattsse** [paradigmxyz/reth#11122]
### Describe the feature

ref #10974 

currently the ethApi impl only tracks the `EvmConfig`:

https://github.com/paradigmxyz/reth/blob/bb27f37cc703789eb41bb084892d44f770868e7d/crates/rpc/rpc/src/eth/core.rs#L216-L217

it would be beneficial to have additional execution related helpers, 

this could serve as the entry point that abstracts away transaction/block execution for tracing, pending block building etc.
This would also decouple execution further from eth API impl, which I believe @tcoratger would also appreciate.

what we need first, is a solution to #10974, an instance that wraps `EvmConfig` and knows how to execute a block.

Which can be something like: https://github.com/paradigmxyz/reth/pull/11074

then we can also integrate the payload builder so we can easily build a pending block

The end goal would probably look like something that doesn't require EvmConfig at all.

**Comment by 0x00101010** [comment]
Hey @mattsse,

I have this [PR](https://github.com/paradigmxyz/reth/pull/11149) that basically injects BlockExecutor into DebugApi for debug_execution_witess purposes, upon reading your issue here, it looks like my approach might not be the best in terms of clean interface.

Would love to get your thoughts on if the PR and if this should be tackled at another layer.
