### ISSUE TITLE
Move block traits into `reth-primitives-traits`

### ISSUE THREAD

**Issue by emhane** [paradigmxyz/reth#11757]
### Describe the feature

Move block traits into `reth-primitives-traits` by changing signatures that return `reth-primitives` types to associated types on the block traits, e.g. `SealedBlock`

https://github.com/paradigmxyz/reth/tree/main/crates/primitives/src/traits/block

**Comment by 0xurb** [comment]
@emhane looks good, can I take it?

**Comment by 0xurb** [comment]
Also proofs usage here

https://github.com/paradigmxyz/reth/blob/d4be773f5f71b49e7e40de3dd747a80af18daf74/crates/primitives/src/traits/block/body.rs#L54-L64

forces to move proofs also somewhere (separate crate / to primitives), but it goes to cyclic dependency, since proofs module use some primitives from `reth-primitives`

**Comment by Rjected** [comment]
Hey! Since this is a high priority issue for the SDK I'll be assigning @emhane to this. I think the proofs do not necessarily need to be default implementations on the trait if they complicate the dependency situation, as we're just moving the traits for now.
