### ISSUE TITLE
Add Geometry to DatabaseArgs

### ISSUE THREAD

**Issue by mattsse** [paradigmxyz/reth#11819]
### Describe the feature

for https://github.com/paradigmxyz/reth/issues/10585

we'd like to make geometry configurable:

https://github.com/paradigmxyz/reth/blob/82862fabd762f2a2b00dd77d140c2c6f5b63cadf/crates/storage/db/src/implementation/mdbx/mod.rs#L281-L289

for this we should first add Geometry to 

https://github.com/paradigmxyz/reth/blob/82862fabd762f2a2b00dd77d140c2c6f5b63cadf/crates/storage/db/src/implementation/mdbx/mod.rs#L64-L64

and initialized with the values we currently use

**Comment by gerceboss** [comment]
@mattsse , would like to work on this issue , can you please assign this to me? . Also wanted to confirm , that if an extra function is needed that takes Geometry from client's side as a parameter? Or just the one initiated will be the final one.

**Comment by evchip** [comment]
I've opened a draft PR to address this issue. The basic functionality is implemented, but I'm seeking advice on how to better handle byte size passed as CLI args (e.g., allowing users to type "4GB" instead of "4294967296").

@gerceboss , I saw your comment about wanting to work on this. I hope you don't mind that I've started on it. If you're interested, there's still work to be done on improving the user input handling for byte sizes. I'd be happy to collaborate or hear your thoughts on this.

@mattsse, I've left a question in the PR about conventions for handling human-readable byte sizes in CLI args. Any guidance would be appreciated.

**Comment by gerceboss** [comment]
@evchip , can you link the PR? Would love to collaborate and contribute wherever I can !

**Comment by evchip** [comment]
> @evchip , can you link the PR? Would love to collaborate and contribute wherever I can !

@gerceboss The PR is linked above, but here it is again for easy reference: #11828. I'd be happy to collaborate with you on this.

As I mentioned in the PR, we need a way to handle human-readable byte sizes in CLI args (e.g., "4GB" instead of "4294967296"). Would you be interested in working on a function that converts these human-readable strings to byte values? If you're up for it, you could:

* Fork my branch
* Implement the converter function
* Add tests for it
* Submit a PR to my branch

This way, we can incorporate your work into the existing PR. What do you think?

**Comment by DanielEmmanuel1** [comment]
Can I be assigned to this?

My Developer Background:
I am a developer with experience in database design and configuration management. My background includes working on systems that require flexible and scalable architecture, enabling effective data handling and storage solutions.

My Proposed Solution To Tackle The Issue:
1. Add a Geometry field to the DatabaseArgs structure.
2. Initialize the Geometry field with the current values used in the system.
3. Ensure that the configuration can be easily updated and accessed.
