### ISSUE TITLE
Include gas/s averages in execution throughput graph

### ISSUE THREAD

**Issue by Rjected** [paradigmxyz/reth#12179]
Right now the execution throughput metric just records a raw gas metric, when it can have a good amount of variation. We should include averages over different time intervals (1m, 5m, 10m, ...) in the graph.

**Comment by edisontim** [comment]
Hey! Can I work on this?

**Comment by Rjected** [comment]
sure! assigned

**Comment by edisontim** [comment]
gm @Rjected I'm having issues testing this. I'm launching the grafana/prometheus/lighthouse/reth stack with the docker compose, I generated the jwt but I'm getting an error with syncing, lighthouse isn't able to get the checkpoint sync because of a Connection timeout to https://mainnet.checkpoint.sigp.io/. 
Have you heard of anything like this happening before?

**Comment by Rjected** [comment]
@edisontim I've never encountered that, but there are many other checkpoint sync urls here if the sigp one doesn't work:
https://eth-clients.github.io/checkpoint-sync-endpoints/

Are you using mainnet? That will take a while to sync, I would recommend using holesky for development
