### ISSUE TITLE
Showcase more advanced Op payload building

### ISSUE THREAD

**Issue by mattsse** [paradigmxyz/reth#12307]
### Describe the feature

with https://github.com/paradigmxyz/reth/pull/12229 we will have an easy way to configure the logic how transactions should be ordered.

this take will look something like

```rust
struct OpPayloadBuilder<EvmConfig, Txs>
```
where `Txs` is responsible for returning a https://github.com/paradigmxyz/reth/blob/c805e2c83acadbb3baafa29c2ce8bfae3793e0e7/crates/transaction-pool/src/traits.rs#L751-L751 instance.

effectively something like

```rust
fn best_transactions_for_block<Pool>(&self, attr: Attributes, pool:Pool) -> impl BestTransactions
```
that is being plugged in like https://github.com/paradigmxyz/reth/blob/c805e2c83acadbb3baafa29c2ce8bfae3793e0e7/crates/optimism/payload/src/builder.rs#L128-L130

the instance of `BestTransactions` could be anything, that even injects new txs manually top of block. Effectively A special iterator that yields txs to include in a block.

A primitive solution for priotising txs was added here:
https://github.com/paradigmxyz/reth/blob/c805e2c83acadbb3baafa29c2ce8bfae3793e0e7/crates/transaction-pool/src/pool/best.rs#L262-L265

but we can add an impl that is more advanced and can even create new txs, or even combine multiple tx sources (regular pool + something else)

cc @sevazhidkov

**Comment by sevazhidkov** [comment]
@mattsse some follow up questions and a proof-of-concept PR to align on the direction to go (#12320)

I was thinking two ways to configure block bundling:
1. Mega-struct with different rules that implements `BestTransactions` and manages sources under the hood
2. Smaller, nested & composable iterators wrapping around other iterators

Approach (2) felt more flexible, extendable and it has less `dyn`. `best.rs` already had higher-order `BetaTransactions` — `BestTransactionsWithPrioritizedSenders` (mentioned in the issue) and `BestTransactionFilter`, felt natural to continue that path and add some more primitives.

Here is an example block composition from PR:
```

        // (1) up to 100 gas: custom top-of-block transaction
        // (2) up to 100 gas: transactions from the priority pool
        // (3) up to 200 gas: only transactions from address A
        // (4) up to 200 gas: only transactions from address B
        // (5) until block gas limit: all transactions from the main pool
```

And implementation:
```
        let block = BestTransactionsChain::new(
            // Segment 1
            BestTransactionsFixed::single(Arc::new(
                f.validated(MockTransaction::eip1559().with_sender(address_top_of_block)),
            )),
            Some(100),
            BestTransactionsChain::new(
                // Segment 2
                priority_pool.best(),
                Some(100),
                // Segment 3
                BestTransactionsWithPrioritizedSenders::new(
                    HashSet::from([address_a]),
                    200,
                    // Segment 4
                    BestTransactionsWithPrioritizedSenders::new(
                        HashSet::from([address_b]),
                        200,
                        // Segment 5
                        pool.best(),
                    ),
                ),
                None,
            ),
            None,
        );
```

There are some issues with this:
```
        // - If prioritized addresses overlap, a single transaction will be prioritized twice and
        //   therefore use the per-segment gas limit twice.
        // - Priority pool and main pool must synchronize between each other to make sure there are
        //   no conflicts for the same nonce. For example, in this scenario, pools can't reject
        //   transactions with seemingly incorrect nonces, because previous transactions might be in
        //   the other pool.
```
(and potentially more stuff, will think through this one more time tomorrow, might miss something, particularly around multi-pool syncronizations).

**Questions**

1. What are you thoughts on the approach above? Should I explore approach (1) more?

> and can even create new txs

2. This part actually might need more state than just `BestTransactionsAttributes` — block number comes to mind, but probably many other things. We're making single-block-use `BestTransactions` objects anyway, so I'm thinking that we can keep it simple and require the builder of `impl BestTransactions` to generate transactions somehow and include them via `BestTransactionsFixed`, instead of trying to generate within a trait implementation. Agree?

3. What's the best place to provide an example (post #12229)? Seems like `examples` does not have any `OptimismNode`, is this by design and should I start one to demonstrate the approach?

**Comment by mattsse** [comment]
cool!

yeah 2) seems more flexible, yep lets continue with this

> // - If prioritized addresses overlap, a single transaction will be prioritized twice and
        //   therefore use the per-segment gas limit twice.
        // - Priority pool and main pool must synchronize between each other to make sure there are
        //   no conflicts for the same nonce. For example, in this scenario, pools can't reject
        //   transactions with seemingly incorrect nonces, because previous transactions might be in
        //   the other pool.

these are all valid, and I think we want to give the builder a better way to convey this by extending `.mark_invalid` with some context, like `NonceTooHigh/Low` so that the iterator can use that information.

> to generate transactions somehow and include them via BestTransactionsFixed

that makes sense. I'm merging #12229 today and introduce some kind of factory trait for BestTransactions, so that this step becomes stateful and we can add more args that include the context, like PayloadAttributes + header, and maybe even the `StateProvider`, something like 

```rust
trait PayloadTransactions {
   fn best(&self, pool, attr, ....) -> Box<dyn BestTransactions>
} 
```

The best make to add config example rn, would be somewhere here:

https://github.com/paradigmxyz/reth/blob/5c2e9417fc16172fde117875d95708f3a5fc6ce3/crates/optimism/node/tests/it/main.rs#L3-L4

the way this would work, would be introducing a new builder:

https://github.com/paradigmxyz/reth/blob/5c2e9417fc16172fde117875d95708f3a5fc6ce3/crates/optimism/node/src/node.rs#L289-L289

or ideally we integrate this trait there as well.

**Comment by sevazhidkov** [comment]
@mattsse added some stub code to the PR for the example (#12320, please check if that's what you had in mind), but actually struggling to add the custom logic right now (the most important part of this example, haha)  — starting with the simple case of `BestTransactionsFixed`. Perhaps, my naive iterator combinator approach is breaking here.

`BestTransactions` is currently an iterator over `ValidPoolTransaction<<Pool as TransactionPool>::Transaction>`. So we actually need to create `ValidPoolTransaction` in `BestTransactions` implementation to maintain the same type. 

1. We seemingly can't add and delete to the pool right away — as a matter of current `TransactionPool` interface, `add_transaction` is async.
2. We can create `ValidPoolTransaction` manually, but this requires faking `SenderId`, because we can't compute in the trait (right?).
3. We can re-arrange the types a little bit? E.g. return enum from BestTransactions that can be a pool-sourced transactions or custom tx?
4. Or we can edit interface of the pool a little bit to allow for ad-hoc non-async add transaction method that are assigned sender ID, but that are not actually going to be stored in the pool.

Let me know if you're leaning towards any of this solution or I should take a step back and come up with alternative plan for all of this.

**Comment by mattsse** [comment]
#12320 is great

> but actually struggling to add the custom logic right now

yeah I expected some complications here.


> We seemingly can't add and delete to the pool right away — as a matter of current TransactionPool interface, add_transaction is async.
>We can create ValidPoolTransaction manually, but this requires faking SenderId, because we can't compute in the trait (right?).

right, so it seems like that the `BesTransactions` isn't the right interface to use for this job, especially because we don't actually need it for execution:

https://github.com/paradigmxyz/reth/blob/4048117bcff47cd720e2bf16a01e031711017040/crates/optimism/payload/src/builder.rs#L765-L765

> We can re-arrange the types a little bit? E.g. return enum from BestTransactions that can be a pool-sourced transactions or custom tx?

definitely, I think we can change https://github.com/paradigmxyz/reth/blob/4048117bcff47cd720e2bf16a01e031711017040/crates/optimism/payload/src/builder.rs#L397-L401 how we want. For this Pr it might make sense to just use `impl Iterator<Item= TransactionSignedRecovered>` and ignore the `mark_invalid` part for now. I'm thinking about that separately now, how to get rid of the `mark_invalid(&Self::Item)` part

> Or we can edit interface of the pool a little bit to allow for ad-hoc non-async add transaction method that are assigned sender ID, but that are not actually going to be stored in the pool.

I think interacting with the pool (adding) is out of scope here and we should instead only consume from the pool.

**Comment by mattsse** [comment]
or instead of doing `impl Iterator<Item= TransactionSignedRecovered>` we can introduce a new trait that is similar to `BestTransactions` but tailor made for block building, because in the future we might want to pass some additional context on `next` (e.g. the current evm state).

like 

```rust
trait PayloadTransactions {

  fn next(&mut self, ctx: () /*TDB this could give the impl access to the current state so that it has access to storage, which can be used to determine priority (eventually) */) 

  fn mark_invalid(&mut self, Address, Nonce)

}
```

**Comment by sevazhidkov** [comment]
@mattsse 100% agree about `PayloadTransactions`. implemented this in the PR, you can do the first pass if you'd like.

I'll need to finish actually starting the node & make the top-of-block transaction real (right now it's a mock) to see it working e2e, then it should be ready for final pass and merge.

**Comment by sevazhidkov** [comment]
@mattsse updated the PR with your suggestion & e2e test with a node that puts custom signed transaction in every block.

Raw ideas from the first experience of implementing the trait (but probably can be addressed in follow up issues / PRs):
* Having async in `PayloadTransactions` would be nice. I'm using a local signed wallet, but I imagine prod users might want to use something like AWS KMS for signing / fetch prices to show in oracle. But I'm seeing that the rest of payload builder is sync, so this might be non-trivial.
  * Or even stream? But it might be harder to implement `Stream` for users.
* Nonce management is an interesting example of problem that might be solved with state context in `PayloadTransactions`. If you're putting transaction on top of block, you'd like to have a helper on the state before the block. But if you're putting transaction at the end of block, you want state at the end of block (in case nonce has updated).

**Comment by mattsse** [comment]
good points, 
everything is sync here because haven't anticipated that we might need async during payload building itself.

maybe it's worth converting this to a stream which would unlock a few other use cases I guess, but encouraging async could also be problematic because all of this should happen asap, but for signing I can see it, though this could also be solved by blocking in place which would be fine here as well.
