### ISSUE TITLE
Extract PayloadTransactions to payload-primitives

### ISSUE THREAD

**Issue by mattsse** [paradigmxyz/reth#12533]
### Describe the feature

we can move:

https://github.com/paradigmxyz/reth/blob/7bd7c37b13960cb5c04b46ec678234596db299d6/crates/transaction-pool/src/traits.rs#L1518-L1518

and implementers

https://github.com/paradigmxyz/reth/blob/7bd7c37b13960cb5c04b46ec678234596db299d6/crates/transaction-pool/src/pool/best.rs#L446-L446

to this crate because this specifically targets payload building

https://github.com/paradigmxyz/reth/blob/7bd7c37b13960cb5c04b46ec678234596db299d6/crates/payload/primitives/Cargo.toml#L2-L2

**Comment by TheDhejavu** [comment]
Took a quick look at the dependency relationship between `reth-transaction-pool` and `reth-payload-primitives`. Currently, `reth-payload-primitives` depends on `reth-transaction-pool` as shown https://github.com/paradigmxyz/reth/blob/7bd7c37b13960cb5c04b46ec678234596db299d6/crates/payload/primitives/Cargo.toml#L19

If we want to move all payload-related implementers and traits to `reth-payload-primitives`, we'll encounter a dependency cycle issue. This is because:
1. We need to call `reth-payload-primitives` in `reth-transaction-pool` tests
2. Moving tests to `reth-payload-primitives` would require making `reth-transaction-pool` related methods that's used in test public

Currently, the only reason for `reth-transaction-pool` dependency in `reth-payload-primitives` is for error handling, as seen here https://github.com/paradigmxyz/reth/blob/7bd7c37b13960cb5c04b46ec678234596db299d6/crates/payload/primitives/src/error.rs#L6


One approach is to remove the `reth-transaction-pool` dependency from `reth-payload-primitives` and only allow `reth-transaction-pool` to depend on `reth-payload-primitives` for payload-related functionality.

the downside is that we won't be able to move this https://github.com/paradigmxyz/reth/blob/7bd7c37b13960cb5c04b46ec678234596db299d6/crates/transaction-pool/src/pool/best.rs#L213 as because it depends `reth-transaction-pool`.

**Comment by mattsse** [comment]
I see, in that case, let's introduce a new crate for this like `payload-util`
this is probably better because eventually we need to put in a bunch of evm stuff in there anyway
