### ISSUE TITLE
`ExecutionPayloadValidator` generic over block

### ISSUE THREAD

**Issue by emhane** [paradigmxyz/reth#13323]
### Describe the feature

Make `ExecutionPayloadValidator` generic over block. Either using `PhantomData` for a block type, or using a generic for block on method signatures that contain `SealedBlock` so it can be generalised as `SealedBlockFor<B>`
https://github.com/paradigmxyz/reth/blob/c553b1e86d8200effda90fff5711870fb25642d1/crates/payload/validator/src/lib.rs#L19-L185

**Comment by klkvr** [comment]
I don't think we can do this because this type performs the ExecutionPayload -> Block conversion. This is abstracted through https://github.com/paradigmxyz/reth/blob/3d5b1657ab846d579da3b7f225b6303670b8be31/crates/engine/primitives/src/lib.rs#L86-L103

For `ExecutionPayloadValidator` we could make it generic over transaction thus allowing to convert to the `Block<T>` type, but entire primitives won't be useful here
