### ISSUE TITLE
Add TxCount Table for Transaction to Block mapping

### ISSUE THREAD

**Issue by mattsse** [paradigmxyz/reth#1699]
### Describe the feature

we need a way to go from Transaction to Block which is currently not possible.

https://github.com/paradigmxyz/reth/pull/1664#discussion_r1131843464
suggests to add a new table for tx count to block number

**Comment by rakita** [comment]
To note here.
It shouldn't be the Count as the index is going to be different. We are modellin ranged here, and we want the `TxNumber` of the last transaction to be tied to the block num, so that this transaction is in the inclusive range.

`TransactionBlock` is probably a better name to show intention.

And blocks that don't have transactions should not be inserted.
