### ISSUE TITLE
Save pendings blocks to database

### ISSUE THREAD

**Issue by rakita** [paradigmxyz/reth#1713]
### Describe the feature

Pending blocks found in BlockchainTree are going to be lost if the node gets restarted for an update or rebooted for any reason. This would make this process go slightly smoother if we are saving all pending blocks and loading them on start of the node.

### Additional context

There is issue with `main_codec` that it can't work on the block as it has both `Header` and `Vec<Withdrawals>` that are unbounded structures.

**Comment by onbjerg** [comment]
Honestly, it's probably better to just discard them and sync from P2P if we crash. It saves space, is probably simpler in terms of startup logic for the blockchain tree and it doesn't really matter if we save the pending blocks or not if the node has been down for a certain amount of time, since the tree will be missing blocks that need to be fetched from P2P.

**Comment by rakita** [comment]
> Honestly, it's probably better to just discard them and sync from P2P if we crash. It saves space, is probably simpler in terms of startup logic for the blockchain tree and it doesn't really matter if we save the pending blocks or not if the node has been down for a certain amount of time, since the tree will be missing blocks that need to be fetched from P2P.

It is a small feature but nevertheless, it is beneficial to have it. It is simple to implement and the only thing blocking it is `main_codec` as atm it can't compress the whole block.
