### ISSUE TITLE
Error: 12

### ISSUE THREAD

**Issue by vcastellm** [paradigmxyz/reth#2211]
### Describe the bug

Reth built correctly in the system, I'm using ARM based OrangePi 5 with a 2TB NVMe disk.

When trying to run the node it errors with the cryptic `Error: 12`

When looking to the said line, it looks like it's unable to open the db. Maybe it's something obvious I'm not doing correctly but I tried several things, including replacing/upgrading the db source files and rebuilding with the same result.

It works well on MacOS ARM M1

### Steps to reproduce

1. run the node `reth node --chain goerli`

### Node logs

```text
2023-04-12T14:54:04.346135Z  INFO reth 0.1.0 starting
2023-04-12T14:54:04.349436Z  INFO Configuration loaded path=/home/vcastellm/.config/reth/goerli/reth.toml
2023-04-12T14:54:04.349562Z  INFO Opening database path=/home/vcastellm/.local/share/reth/goerli/db
Error: 12

Location:
    /home/vcastellm/reth/crates/staged-sync/src/utils/init.rs:15:14 vcastellm@orangepi5:~$ reth node --chain goerli
2023-04-12T14:54:04.346135Z  INFO reth 0.1.0 starting
2023-04-12T14:54:04.349436Z  INFO Configuration loaded path=/home/vcastellm/.config/reth/goerli/reth.toml
2023-04-12T14:54:04.349562Z  INFO Opening database path=/home/vcastellm/.local/share/reth/goerli/db
Error: 12

Location:
    /home/vcastellm/reth/crates/staged-sync/src/utils/init.rs:15:14
```
```


### Platform(s)

Linux (ARM)

### What version/commit are you on?

ca28b37a742ccad0c387e69121ffb842190151fa

### Code of Conduct

- [X] I agree to follow the Code of Conduct

**Comment by vcastellm** [comment]
Thanks @Rjected can you point to the PR with the change to data dirs?

**Comment by gakonst** [comment]
> ARM based OrangePi 5 with a 2TB NVMe disk.

Do you mind giving some more system information? What's `uname -a`? I have not tested MDBX on such a device before, so unsure myself - maybe @erthink knows?

**Comment by vcastellm** [comment]
Sure:

`Linux orangepi5 5.10.110-rockchip-rk3588 #23.02.2 SMP Fri Feb 17 23:59:20 UTC 2023 aarch64 aarch64 aarch64 GNU/Linux`

I'm using Armbian distro for this board, I can try anything at this point, thinking in trying with a different distro.

**Comment by gakonst** [comment]
Yeh other distro would be helpful, but I suspect it's got to do with the Pi..

**Comment by vcastellm** [comment]
Same error using Debian bullseye but in this case the error message is present:

```
2023-04-13T07:35:02.601874Z  INFO Opening database path=/root/.local/share/reth/goerli/db
Error: Failed to open database: 12

Location:
    /root/reth/crates/staged-sync/src/utils/init.rs:15:14
```

Looks like it should have something to do with mem and MDBX lib compilation.

**Comment by vcastellm** [comment]
Thanks for the suggestion @mattsse, I tried playing with these values, I reduced it a little didn't work, then come with a combination that "works", I don't know if the values can be higher, I'm going to try a bit more:

```
.set_geometry(Geometry {
                    size: Some(0..(1024 * 1024 * 1)), // TODO: reevaluate (4 tb)
                    growth_step: Some(1024 * 1024 * 128),           // TODO: reevaluate (256 mb)
                    shrink_threshold: None,
```

**Comment by mattsse** [comment]
ty this is very valuable feedback,

@rkrasiuk or @rakita probably have more insight into these settings

**Comment by vcastellm** [comment]
Thanks @mattsse 

It works with 4gb:

```
.set_geometry(Geometry {
                    size: Some(0..(1024 * 1024 * 1024 * 4)), // TODO: reevaluate (4 tb)
                    growth_step: Some(1024 * 1024 * 256),           // TODO: reevaluate (256 mb)
```

So would be great to know more about that 4 tb mark.

**Comment by mattsse** [comment]
looks like this hasn't been touched in a while, so now is a good time to "reevaluate" the todo,
not exactly sure what the `size` field refers to but if this is the expected size of the db, then 4tb is way too high

**Comment by 0xpanoramix** [comment]
Hi,

I ran into the same issue as described above (except that the piece of code [is now available here](https://github.com/paradigmxyz/reth/blob/b7c977765c5491186e041086d8199cc25a559f0f/crates/storage/db/src/implementation/mdbx/mod.rs#L71)).

After a bit of research, it seems that the error has indeed something to do with memory allocation.
The same error is also raised [in libmdbx here](https://github.com/paradigmxyz/reth/blob/b7c977765c5491186e041086d8199cc25a559f0f/crates/storage/libmdbx-rs/mdbx-sys/libmdbx/mdbx.c#L17102):
```c
MDBX_env *env = osal_calloc(1, sizeof(MDBX_env));
if (unlikely(!env))
    return MDBX_ENOMEM;
```

From what I have understood, it goes like this:

1. In reth's [`open`](https://github.com/paradigmxyz/reth/blob/b7c977765c5491186e041086d8199cc25a559f0f/crates/storage/db/src/implementation/mdbx/mod.rs#L62) method, a call is made to the [`open_with_permissions`](https://github.com/paradigmxyz/reth/blob/b7c977765c5491186e041086d8199cc25a559f0f/crates/storage/libmdbx-rs/src/environment.rs#L405) method.
2. Then, an FFI call is made to the C implementation of [`mdbx_env_create`](https://github.com/paradigmxyz/reth/blob/b7c977765c5491186e041086d8199cc25a559f0f/crates/storage/libmdbx-rs/mdbx-sys/libmdbx/mdbx.c#L17065).
3. MDBX fails to allocate memory based on the provided configuration.
4. The error is propagated back to Reth.

So it seems that depending on the `MDBX_env`'s content, the allocation can fail and cause the issue.
On my setup - OrangePi 5 / 16GB RAM / Armbian - I can set the geometry size field up to 342GB, and then the error appears.

My plan is to investigate on why the allocation fails - maybe something related to the [MDBX_env's structure content](https://github.com/paradigmxyz/reth/blob/b7c977765c5491186e041086d8199cc25a559f0f/crates/storage/libmdbx-rs/mdbx-sys/libmdbx/mdbx.c#L3602) ? - but if someone has an idea or suggestion I'm definitely open to it !

**Comment by onbjerg** [comment]
The upper bound of `size` in `Geometry` governs how big the database can get. It also defines the linear address space reservation in each process that opens the database.

Changing the upper bound is costly according to MDBX docs, so a reasonably large value had to be chosen. Since we are at 2tb, the assumption here was that we would probably grow to 3tb "relatively soon", so 4tb was chosen.

If the size is set to only 342gb, then reth cannot store more than 342gb of data. This is not sufficient to sync.

As far as I can tell, [x86_64] has a 48-bit address space that is divided in half, which means that user-space and kernel each have 128TB of address space.

On [AArch64] however, it seems that the address space is only 512GB for user space and 256TB for the kernel.

In the linked document above, it seems that some newer version of ARM has support for Large Virtual Address space, but it requires running with a 64KB page size. I am not sure how (or if) you can enable this.

**Comment by onbjerg** [comment]
Looking at the above doc again, it looks like AArch64 does actually support 4-level paging, so I checked out the board you are using to see if it is restricted to 3 levels, but it seems like there isn't a reason it should be - the OrangePi 5 uses a Rockchip RK3588S, which according to their [datasheet](https://www.cnx-software.com/pdf/datasheet/Rockchip-RK3588S-Datasheet%20V1.0-20211221.pdf) is based on ARMv8-A. ARMv8-A [should support 4 level paging](https://developer.arm.com/documentation/den0024/a/The-Memory-Management-Unit/Translation-tables-in-ARMv8-A/Effect-of-granule-sizes-on-translation-tables).

I wonder if it is due to the distros used/the config used to build the kernel?

**Comment by shuklaayush** [comment]
I've seen a similar issue in the erigon repo where it was due to kernel config problem as @onbjerg mentioned. Tagging it here for reference
https://github.com/ledgerwatch/erigon/issues/4871#issuecomment-1229275707

**Comment by 0xpanoramix** [comment]
Quick update, I was able to fix the issue by recompiling Armbian and setting a 64KB page size in the process.

I am finishing a blog post describing the entire process, but I think it might be relevant to document it somewhere close to the source code, wdyt @onbjerg ? If so, where should be the most appropriate place ?
The process is "fast" on Armbian as it provides an easy-to-use build framework, but might be a bit more tedious on other distros.

**Comment by gakonst** [comment]
@0xpanoramix amazing. we can maybe add a subsection on https://paradigmxyz.github.io/reth/installation/installation.html? 

https://github.com/paradigmxyz/reth/tree/main/book/installation

**Comment by vcastellm** [comment]
@0xpanoramix does the process involves modifying the source and recompiling?

**Comment by 0xpanoramix** [comment]
@vcastellm Not at all, it just involves building a new Armbian image (if you're using an SD card on the Orange Pi, the flash part will be automatically made by the build framework). Then, the default binary from the releases will work.

@gakonst Can I take the task about writing the new subsection in the documentation ? I already have most of the content from my article, I just need to make it more "formal".

**Comment by gakonst** [comment]
> @gakonst Can I take the task about writing the new subsection in the documentation ? I already have most of the content from my article, I just need to make it more "formal".


By all means!

**Comment by vcastellm** [comment]
Closing this as the instructions in docs allows for successful building of the project in ARM SoCs

**Comment by AndreMiras** [comment]
Thanks a lot for tracking down this bug and working on that doc (https://github.com/paradigmxyz/reth/blob/v0.1.0-alpha.10/book/installation/build-for-arm-devices.md).
For what it's worth, I did also get the issue with the official Orange Pi Ubuntu image, but not with thirdparty Ubuntu one from https://github.com/Joshua-Riek/ubuntu-rockchip.
To be more precise, I'm now using the `ubuntu-22.04.3-preinstalled-desktop-arm64-orangepi-5-plus.img.xz` image from https://github.com/Joshua-Riek/ubuntu-rockchip/releases/tag/v1.27
And the official image with the issue was `Orangepi5plus_1.0.6_ubuntu_jammy_desktop_gnome_linux5.10.110.7z` from https://drive.google.com/drive/folders/1wOmKUla8CwUPTfxvfCGutj8lbMZFtFCm
