### ISSUE TITLE
make reth cli crate consumeable

### ISSUE THREAD

**Issue by mattsse** [paradigmxyz/reth#2348]
### Describe the feature

the reth binary crate contains all commands and configures the node specifically for reth.

To make any modifications, at least the reth cli crate would have to be forked.

In order to make modifications more ergonomic, the node command should be configurable, so all boilerplate setup code can be reused easily.

This would be possible if there's an abstraction over a CLI trait or similar that provides all components required by `execute` function.

So the ideal DX would be:
* configure the node via a type that satisfies the CLI trait
* feed the type to a CLI executor or something

the simplest solution would be to start with a generic `Cli` type that replaces the node command entirely so that the `node::Command` is generic over something that can be executed, by default, this is reth's node command.

**Comment by onbjerg** [comment]
I think alternatively we should just revisit having a node builder, i.e. two structs `Node` and `NodeBuilder` to setup and configure everything that we do in `reth node` right now, and then have the CLI consume that. It is unlikely that you would want to customize any of the other parts of the CLI anyway, and if you wanted to, you could do that right now since most use 1-2 components
