### ISSUE TITLE
Panic at MerkleExecute on Goerli

### ISSUE THREAD

**Issue by yorickdowne** [paradigmxyz/reth#2538]
### Describe the bug

Reth commit 90fa586ced2d5e732fadc1cea89e1bfc68e1cab8 panics at MerkleExecute on Goerli

### Steps to reproduce

Sync Reth with Lighthouse on Goerli

### Node logs

```text
reth-test-execution-1  | 2023-05-03T12:40:04.157976Z INFO Executing stage stage=MerkleExecute from=0
reth-test-execution-1  | thread 'tokio-runtime-worker' panicked at 'range end index 3840 out of range for slice of length 3266', crates/primitives/src/checkpoints.rs:73:42
reth-test-execution-1  | note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
reth-test-execution-1  | 2023-05-03T12:40:04.158168Z ERROR Critical task `pipeline` panicked: Any { .. }
reth-test-execution-1  | 2023-05-03T12:40:04.158230Z ERROR Failed to receive pipeline result error=RecvError(())
reth-test-execution-1  | 2023-05-03T12:40:04.159916Z  INFO Wrote network peers to file peers_file="/home/reth/.local/share/reth/goerli/known-peers.json"
reth-test-execution-1  | Error: Critical task panicked pipeline
reth-test-execution-1  | 
reth-test-execution-1  | Location:
reth-test-execution-1  |     /rustc/84c898d65adf2f39a5a98507f1fe0ce10a2b8dbc/library/core/src/convert/mod.rs:726:9
reth-test-execution-1  | 2023-05-03T12:40:05.338657Z INFO reth 0.1.0 starting
```

### Platform(s)

Linux (x86)

### What version/commit are you on?

90fa586ced2d5e732fadc1cea89e1bfc68e1cab8 

### Code of Conduct

- [X] I agree to follow the Code of Conduct

**Comment by rkrasiuk** [comment]
hey @yorickdowne, since merkle is invalid anyway, you can just run `reth drop-stage merkle --chain goerli` to address this. the checkpoint structure has been altered in this PR https://github.com/paradigmxyz/reth/pull/2512.

Regarding the original https://github.com/paradigmxyz/reth/issues/2504, let me break it down: the primary cause of the unwind was invalid state root. It led to unwind and since reth is not good at handling unwinds with large block ranges that led to OOM

The unwind issue is known and we'll make sure to address it. Invalid state root however was caused by a bug in revm https://github.com/bluealloy/revm/pull/475. The fix is included in https://github.com/paradigmxyz/reth/pull/2547. After it's merged, you can resync the node. I can confirm it works past block 8mil, still syncing to the tip

**Comment by gakonst** [comment]
Confirming the above... I'd run the drop-stage command and rerun the node. Confirming this also worked.

**Comment by gakonst** [comment]
https://github.com/paradigmxyz/reth/issues/2510 yep - tracking here, it should be really easy.

**Comment by rkrasiuk** [comment]
it isn't a slot, but rather the balance of `0x8a5c64b886be93db05f192ee7b22948406313a37` account. it should be `0` instead of `uint256::max`

**Comment by gakonst** [comment]
@yorickdowne confirming fixed / can close?

**Comment by yorickdowne** [comment]
Yep fixed!
