### ISSUE TITLE
Add toolchain file 

### ISSUE THREAD

**Issue by samtvlabs** [paradigmxyz/reth#2821]
### Describe the feature

The `rustfmt.toml` file currently implement some formatting rules that are only available in nightly. 

```shell

<-- snip -->
Warning: can't set `wrap_comments = true`, unstable features are only available in nightly channel.
Warning: can't set `comment_width = 100`, unstable features are only available in nightly channel.
Warning: can't set `imports_granularity = Crate`, unstable features are only available in nightly channel.
Warning: can't set `binop_separator = Back`, unstable features are only available in nightly channel.
Warning: can't set `trailing_semicolon = false`, unstable features are only available in nightly channel.
Warning: can't set `trailing_comma = Vertical`, unstable features are only available in nightly channel.
Warning: can't set `wrap_comments = true`, unstable features are only available in nightly channel.
Warning: can't set `comment_width = 100`, unstable features are only available in nightly channel.
Warning: can't set `imports_granularity = Crate`, unstable features are only available in nightly channel.
Warning: can't set `binop_separator = Back`, unstable features are only available in nightly channel.
Warning: can't set `trailing_semicolon = false`, unstable features are only available in nightly channel.
Warning: can't set `trailing_comma = Vertical`, unstable features are only available in nightly channel.
Warning: can't set `wrap_comments = true`, unstable features are only available in nightly channel.
Warning: can't set `comment_width = 100`, unstable features are only available in nightly channel.
```

## Proposed Solution

Add a `rust-toolchain.toml` file to select the nightly toolchain. 

```toml
[toolchain]
channel = "nightly"
```

**Comment by onbjerg** [comment]
This is not planned; our code is supposed to work on stable only, but our lints are nightly. This is also outlined in the contributing docs:

>cargo +nightly fmt -- --check
>cargo +nightly clippy --all --all-features -- -D warnings

https://github.com/paradigmxyz/reth/blob/main/CONTRIBUTING.md#resolving-an-issue

**Comment by samtvlabs** [comment]
Apologies should have read that. Thanks!

**Comment by michaelsproul** [comment]
Why does Reth need nightly for formatting and lints?

This approach is somewhat non-standard, and introduces a bit of friction with some people's Rust tooling. Previously when contributing to Reth I was manually reverting the semicolon changes made by my editor running stable `rustfmt`, where the `trailing_semicolons = false` setting was ignored. To make matters worse, the semicolons introduced by stable `rustfmt` are not removed when running `rustfmt +nightly` (I guess because the lint is unstable and conservative). I've finally got a better setup now by hardcoding an exception for Reth in my `vimrc`:

```vim
if expand('%:p:h') =~ 'reth'
  let g:rustfmt_command = "rustfmt +nightly"
endif
```
