### ISSUE TITLE
Failing Pre-TTD ForkchoiceUpdated After PoS Switch test

### ISSUE THREAD

**Issue by mattsse** [paradigmxyz/reth#2956]
### Describe the bug

This test verifies that a forkchoiceUpdated fails on hash being set to a pre-TTD block after PoS change and simply sends an FCU with the genesis block

reth's supposed to send

{"payloadStatus":{"status":"INVALID","latestValidHash":"0x0000000000000000000000000000000000000000000000000000000000000000","validationError":null}

### Steps to reproduce

./hive --client reth --sim ethereum/engine --sim.limit "/Failing Pre-TTD ForkchoiceUpdated After PoS Switch"

### Code of Conduct

- [X] I agree to follow the Code of Conduct

**Comment by Rjected** [comment]
This is failing due to pre-merge checks in the tree, caused by auto-seal forkchoice updates.
On the first FCU, for the second block, the pipeline runs.
On the third block:
 * the auto seal client issues a forkchoice update
 * then, reth attempts to download the block. this uses the auto seal download clients
 * when reth receives the block, it tries to insert it into the tree.
   * TTD is 196610
   * genesis block has a difficulty of 196608
   * the second block has a difficulty of 1 (196609 TD)
   * the third block has a difficulty of 1 (196610 TD)

The insert happens on the third block, but its parent total difficulty is passed here:
https://github.com/paradigmxyz/reth/blob/171166e84ae75f2129d9c3a9abe504d574d2c587/crates/blockchain-tree/src/blockchain_tree.rs#L377-L384

this check fails, causing the chain to stall before it reaches "The merge", and the test does not start

I forget exactly why passing the parent total difficulty here is the right thing to do. If it is the correct check, then we could solve this by changing the default difficulty for auto seal blocks from 1 to 2, so the total difficulty is reached by the pipeline run on the first FCU
