### ISSUE TITLE
Add custom chain id in --chain custom file

### ISSUE THREAD

**Issue by manylov** [paradigmxyz/reth#3038]
### Describe the feature

Trying to run localnet node with --chain ./mainnet.json
Got mainnet.json from https://github.com/paradigmxyz/reth/blob/main/crates/primitives/res/genesis/mainnet.json
Added my own wallet with some balance to alloc section
Got error: Genesis hash mismatch: expected 0x1d47…8d90, got 0xd4e5…8fa3

Suppose there is some hardcoded hash for mainnet.
Please add ability to describe custom chain id in mainnet.json file to spin up own localnet

**Comment by onbjerg** [comment]
@manylov This is not because of the chain ID, it is because the state root no longer matches. The state root for `mainnet.json` can be found here: 

https://github.com/paradigmxyz/reth/blob/7cc69d52c6017eeb4348c824a9f5369400e331d1/crates/primitives/res/genesis/mainnet.json#L9

In order for a custom version to work, you would have to recalculate the state root and update it in the file you are passing in.

**Comment by gakonst** [comment]
@onbjerg how should Maksim generate the state root himself? Should we do the state root calculation for the user for any json file they load? I thought we already do that for the known genesis files.

**Comment by onbjerg** [comment]
Upon an extra look, it seems like we do generate state roots on the fly, so it is just that there was an existing database for another chain present.
