### ISSUE TITLE
rename or document`progress` in ControlFlow

### ISSUE THREAD

**Issue by mattsse** [paradigmxyz/reth#3237]
### Describe the feature

`progress` terminology is confusing and not documented clearly what this means:

https://github.com/paradigmxyz/reth/blob/b9c19e82b252b18d1d9f021e7170e06e5ba4cb0f/crates/stages/src/pipeline/ctrl.rs#L3-L44

This should state what this represents exactly

**Comment by tcoratger** [comment]
@mattsse I would suggest to rename each `progress` by `block_number` because that's what it's all about, giving:
- `ControlFlow::Continue { block_number }`
- `ControlFlow::NoProgress { stage_block_number }`

What do you think?

**Comment by mattsse** [comment]
I think this should be block_number

but would like to get @shekhirin opinion on this first

**Comment by tcoratger** [comment]
@mattsse If the changes are:
- `ControlFlow::Continue { progress }` to `ControlFlow::Continue { block_number }`
- `ControlFlow::NoProgress { stage_progress }` to ControlFlow::NoProgress { stage_block_number }

I can handle that :)

**Comment by shekhirin** [comment]
Agree on `block_number`, and I think it should be `block_number` for both `Continue` and `NoProgress` variants, because we're talking about stages in both cases. Let's also tidy up the comments of these fields, because they mean the same: block number the stage has reached (either it progressed and emitted `Continue` or didn't have any progress and emitted `NoProgress`)
