### ISSUE TITLE
Missing Stage Checkpoint Data After Metrics Port Closed.  

### ISSUE THREAD

**Issue by 0xcacti** [paradigmxyz/reth#3251]
### Describe the bug

To test, I temporarily closed some ports on the firewall.  After, re-opening the stage checkpoint data was missing. 
![image](https://github.com/paradigmxyz/reth/assets/97139981/f3b54c0f-2730-4c96-bb95-345fa04130cb)

### Steps to reproduce

Close ports with software or hardware firewall 

### What version/commit are you on?

version: 0.1.0, Commit SHA: 6ef3e12f

### What database version are you on?

reth db version is not a command or an option. 

reth/target/maxperf/reth db --datadir /mnt/data/reth/ --help
Database debugging utilities

Usage: reth db [OPTIONS] <COMMAND>

Commands:
  stats
          Lists all the tables, their entry count and their size
  list
          Lists the contents of a table
  get
          Gets the content of a table for the given key
  drop
          Deletes all database entries
  help
          Print this message or the help of the given subcommand(s)

Options:
      --datadir <DATA_DIR>
          The path to the data dir for all reth files and subdirectories.

          Defaults to the OS-specific data directory:

          - Linux: `$XDG_DATA_HOME/reth/` or `$HOME/.local/share/reth/`
          - Windows: `{FOLDERID_RoamingAppData}/reth/`
          - macOS: `$HOME/Library/Application Support/reth/`

          [default: default]

      --chain <CHAIN_OR_PATH>
          The chain this node is running.

          Possible values are either a built-in chain or the path to a chain specification file.

          Built-in chains:
          - mainnet
          - goerli
          - sepolia

          [default: mainnet]

  -h, --help
          Print help (see a summary with '-h')

Logging:
      --log.persistent
          The flag to enable persistent logs

      --log.directory <PATH>
          The path to put log files in

          [default: /home/ubuntu/.cache/reth/logs]

      --log.journald
          Log events to journald

      --log.filter <FILTER>
          The filter to use for logs written to the log file

          [default: error]

Display:
  -v, --verbosity...
          Set the minimum log level.

          -v      Errors
          -vv     Warnings
          -vvv    Info
          -vvvv   Debug
          -vvvvv  Traces (warning: very verbose!)

  -q, --quiet
          Silence all log output

### Code of Conduct

- [X] I agree to follow the Code of Conduct

**Comment by onbjerg** [comment]
Depending on what ports you closed, you either lost connection to Prometheus, or Prometheus lost connection to the metrics endpoint. In both cases, it should resolve after a while, since Prometheus will try to scrape (with a backoff) continually in the second case, and in the first case it should be a matter of just refreshing

It's not really something we can do anything about (as it is expected), if anything it would more likely be a Grafana or a Prometheus issue - reth just serves metrics over HTTP to Prometheus, nothing else. As long as Prometheus can hit the endpoint, and as long as you can talk to Prometheus, everything should work
