### ISSUE TITLE
stop syncing if available disk size is very low

### ISSUE THREAD

**Issue by jsvisa** [paradigmxyz/reth#3378]
### Describe the feature

I'm running reth in a 2TB NVME, in case of out-of-disk results to the mdbx corrupted, if reth can check and automatically stop the sever if available disk size is very low(eg: 10GB), it will be more safe.

**Comment by onbjerg** [comment]
Hey! Thanks for the suggestion. I am going to close this issue, because I don't think tracking disk size and stopping sync makes a lot of sense. Ideally, you would set up monitoring of disk size, and an alert for when you run low. If we stop the node without the operator knowing, it could have consequences for stakers, and I would rather they shut it down themselves (allowing to set up failovers etc. for themselves) so they know what's going on

**Comment by jsvisa** [comment]
@onbjerg go-ethereum has this flag:

```
 --datadir.minfreedisk value         Minimum free disk space in MB, once reached triggers auto shut down (default = --cache.gc converted to MB, 0 = disabled)
```

ref https://github.com/ethereum/go-ethereum/blob/master/cmd/utils/flags.go#L114-L118
