### ISSUE TITLE
Fix clippy errors 

### ISSUE THREAD

**Issue by rkrasiuk** [paradigmxyz/reth#3544]
https://github.com/paradigmxyz/reth/pull/3540 silenced some annoying clippy errors.

They need to fixed either by upgrading deps or opening issues in corresponding repos:
![Screenshot 2023-07-03 at 14 09 29](https://github.com/paradigmxyz/reth/assets/25429261/5e9bc54b-c63e-491c-bd8b-1790baaa628d)

To repro run `cargo clippy --all --all-features` on latest nightly

**Comment by tcoratger** [comment]
@rkrasiuk What is the last nightly you considered? Following [this](https://releases.rs/docs/1.72.0/), I've `1.72.0` and I've no error running `cargo clippy --all --all-features`

**Comment by rkrasiuk** [comment]
i've ran it on `rustc 1.72.0-nightly (839e9a6e1 2023-07-02)` <- date matters

**Comment by cjeva10** [comment]
The incorrect implementation of `clone` on `Copy` type errors are from parity's `fixed-hash` crate. `construct_fixed_hash` implements `clone` by creating a new fixed hash with zero bits rather than dereferencing self (replace clone function body with `*self`).

Not sure if changing this behavior would screw things up elsewhere though.
