### ISSUE TITLE
Throw better error when duplicate RPC namespaces are specified

### ISSUE THREAD

**Issue by shekhirin** [paradigmxyz/reth#3703]
### Describe the feature

Currently, if you try to run `reth --http --http.api trace,trace`, you will get:
```console
thread 'main' panicked at 'No conflicts: MethodAlreadyRegistered("trace_block")',
/Users/fineas/reth/crates/rpc/rpc-builder/src/lib.rs:855:35
```

which is a correct behaviour with a non-obvious error message. We need to throw a better self-explanatory error.

**Comment by mattsse** [comment]
this should either be detected here in the clap parser

https://github.com/paradigmxyz/reth/blob/4b261cef45768ef2bc597e799c0ffb80e4583168/bin/reth/src/args/rpc_server_args.rs#L469

or directly in the fromstr impl 

I think the former makes more sense

**Comment by Evalir** [comment]
gm, happy to take this

**Comment by onbjerg** [comment]
assigned!

**Comment by ungaro** [comment]
hi @mattsse @onbjerg, 
i've removed duplicates in this line as you've suggested, so it works when you run reth --http --http.api trace,trace without giving any error.

`val.split(',').map(str::trim).collect::<std::collections::HashSet<_>>().into_iter().collect::<Vec<_>>().join(", ").parse::<RpcModuleSelection>().map_err(|err| {`

It's my first contribution, and since i didn't saw any activity in this issue for a while, wanted to give it a try.

can create a PR if it's fine.

thanks

**Comment by mattsse** [comment]
nice, ty.
pleas do

**Comment by ungaro** [comment]
#4418
