### ISSUE TITLE
Store logs in different folders based on the chain

### ISSUE THREAD

**Issue by Rjected** [paradigmxyz/reth#3858]
### Describe the feature

Currently logs are output to `~/.cache/reth/logs/reth.log`, even if there are multiple nodes running on different chains. Instead, logs should be output to `~/.cache/reth/logs/<chain>/reth.log`, or moved to the already-chain-specific `--datadir`. For example:
```
~/.cache/reth/logs/mainnet/reth.log
```
```
~/.cache/reth/logs/sepolia/reth.log
```

**Comment by Rjected** [comment]
> Hi, could I take this issue? It would be my first issue for Reth. Maybe if you can please add more context it could help me solving the issue.

Awesome! I forgot to mention the crucial detail that this relates to the default `--log.persistent` flag behavior.

**Comment by Rjected** [comment]
Just assigned you, I can give pointers on the code if you're having trouble!

**Comment by alessandromazza98** [comment]
I found this part of code:

https://github.com/paradigmxyz/reth/blob/39cd0e071ef1220aef2c54d2d880c4a123e8a638/bin/reth/src/cli.rs#L90C1-L115C2

And then these two functions 

https://github.com/paradigmxyz/reth/blob/39cd0e071ef1220aef2c54d2d880c4a123e8a638/bin/reth/src/dirs.rs#L45C1-L57C2

I think to implement something like for the config files that are already separated with chain name.

**Comment by alessandromazza98** [comment]
Okay I understand the process as a whole now.

However, it is not clear to me exactly where the `log_directory` field of `Logs` is actually registered. Or rather, from what I understand, there is this piece of code, which is the first one that runs:

```rust
/// Parse CLI options, set up logging and run the chosen command.
pub fn run() -> eyre::Result<()> {
    let opt = Cli::parse();

    let mut layers = vec![reth_tracing::stdout(opt.verbosity.directive())];
    let _guard = opt.logs.layer()?.map(|(layer, guard)| {
        layers.push(layer);
        guard
    });
...
```

In the `opt.logs.layer()` function, if there is the flag `--log.persistent`, it sets the log file but it already has the directory `self.log_directory`, where `self` is of type `Logs`. Here is the code:

```rust
impl Logs {
    /// Builds a tracing layer from the current log options.
    pub fn layer<S>(&self) -> eyre::Result<Option<(BoxedLayer<S>, Option<FileWorkerGuard>)>>
    where
        S: Subscriber,
        for<'a> S: LookupSpan<'a>,
    {
        let filter = EnvFilter::builder().parse(&self.filter)?;

        if self.journald {
            Ok(Some((reth_tracing::journald(filter).expect("Could not connect to journald"), None)))
        } else if self.persistent {
            let (layer, guard) = reth_tracing::file(filter, &self.log_directory, "reth.log");
            Ok(Some((layer, Some(guard))))
        } else {
            Ok(None)
        }
    }
}
```

I think the directory is set with the default value for `PlatformPath<LogsDir>`, which is the one without the chain name in the path. 

What I miss is where can I modify this default behaviour in order to let it be dependent on the chain name.

**Comment by risingsun007** [comment]
I am new here so this comment might not be the most accurate.   It looks like chain variable is defined in the subcommands, (chain, node, p2p, ...) 
https://github.com/paradigmxyz/reth/blob/0b012ab6640f7627a0f9fe11ea9eec10d479de72/bin/reth/src/node/mod.rs#L114-L121


 
However, the chain variable is not define in cli.rs  in the Cli struct or Logs struct
https://github.com/paradigmxyz/reth/blob/0b012ab6640f7627a0f9fe11ea9eec10d479de72/bin/reth/src/cli.rs#L78-L81

Maybe adding a variable to the Cli struct with the clap option "global" makes sense.
```rust 
struct Cli {
    /// The command to run
    #[clap(subcommand)]
    command: Commands,

    #[arg(
      global=true,
      long,
      value_name = "CHAIN_OR_PATH",
      verbatim_doc_comment,
      default_value = "mainnet",
      value_parser = genesis_value_parser
  )]
    chain: Arc<ChainSpec>,
```

and on the submodules define the chain variables via
```
 #[arg(from_global)]
   (chain: Arc<ChainSpec>,
```

**Comment by alessandromazza98** [comment]
Ok I managed to create a partial solution (right now also if --datadir is selected it still put logs files in ~/.cache/reth/logs/<chain>/reth.log).

I did something very similar to what @risingsun007 wrote.

1. Put a chain argument inside the Cli struct, with global = true option.
2. In every subcommand I just edit the chain argument to be `#[arg(from_global)]`

The program now works as desired.
- If i run `reth node --log.persistent` it creates logs in ~/.cache/reth/logs/mainnet/reth.log.
- If i run `reth node --chain sepolia --log.persistent` it creates logs in ~/.cache/reth/logs/sepolia/reth.log.

And so on.

The problem is that right now when I try to run tests with `cargo test --all --all-features`, there is this test that fails:

```
thread 'db::tests::parse_stats_globals' panicked at 'Mismatch between definition and access of `chain`. Unknown argument or group id.  Make sure you are using the argument id and not the short or long flags
```

This is the test:
```rust
fn parse_stats_globals() {
        let cmd = Command::try_parse_from(["reth", "stats", "--datadir", "../mainnet"]).unwrap();
        assert_eq!(cmd.datadir.as_ref(), Some(Path::new("../mainnet")));
    }
```

I debugged it and the problem is that `cmd` does not have a `chain` argument, while the `try_parse_from` is looking for it.

I thought that `cmd` should also contain a `chain` argument, since I put the annotation `#[arg(from_global)]` on it, in this way:

```rust
/// `reth db` command
#[derive(Debug, Parser)]
pub struct Command {
    /// The path to the data dir for all reth files and subdirectories.
    ///
    /// Defaults to the OS-specific data directory:
    ///
    /// - Linux: `$XDG_DATA_HOME/reth/` or `$HOME/.local/share/reth/`
    /// - Windows: `{FOLDERID_RoamingAppData}/reth/`
    /// - macOS: `$HOME/Library/Application Support/reth/`
    #[arg(long, value_name = "DATA_DIR", verbatim_doc_comment, default_value_t, global = true)]
    datadir: MaybePlatformPath<DataDirPath>,

    /// The chain this node is running.
    ///
    /// Possible values are either a built-in chain or the path to a chain specification file.
    ///
    /// Built-in chains:
    /// - mainnet
    /// - goerli
    /// - sepolia
    #[arg(from_global)]
    chain: Arc<ChainSpec>,

    #[clap(flatten)]
    db: DatabaseArgs,

    #[clap(subcommand)]
    command: Subcommands,
}
```

I am now trying to deep dive more into this problem!

**Comment by 0xprames** [comment]
hey @alessandromazza98 any luck? I was wondering if you were still working on this - I'd be down to take a look if not

**Comment by risingsun007** [comment]
Using  #[arg(from_global)] in the subcommand struct breaks the test since you are only testing the subcommand as a command.  I think you can just leave the subcommands unchanged and still add the chain variable to the struct Cli with the "global = true" option.

**Comment by alessandromazza98** [comment]
> hey @alessandromazza98 any luck? I was wondering if you were still working on this - I'd be down to take a look if not

Hi, I'm working on it and finally I think I found a solution. I will do a PR today

> Using #[arg(from_global)] in the subcommand struct breaks the test since you are only testing the subcommand as a command. I think you can just leave the subcommands unchanged and still add the chain variable to the struct Cli with the "global = true" option.

Thanks for this advice. Actually it works in this way. I didn't think about it because I was thinking that `from_global` was necessary in order to the `chain` field to be shared on the subcommands but it turned out it's not.
