### ISSUE TITLE
Error when sending duplicate "Data" and "Input" Fields

### ISSUE THREAD

**Issue by 0xJchen** [paradigmxyz/reth#3875]
### Describe the bug

When sending an eth rpc call with duplicate "Data" and "Input" Fields, it reports:

```
{"jsonrpc":"2.0","error":{"code":-32602,"message":"Invalid params","data":"duplicate field `data` at line # column #"},"id":5}%
```

This is problematic when interacting RETH with web3js for reading a contract, as web3js will send both fields [by default](https://github.com/web3/web3.js/blob/f5b4d7d0f14e721380e4c9249a063a3dc982a540/packages/web3-eth/src/utils/transaction_builder.ts#L180) (thanks Zootree for pointing this out on the telegram group).

He also points out a temporary solution:

Commenting ` #[serde(rename = "input")]` [here](https://github.com/paradigmxyz/reth/blob/main/crates/rpc/rpc-types/src/eth/call.rs)

### Steps to reproduce

Send an eth rpc call with duplicate "Data" and "Input" Fields

For example, calling the `getReserves` function of `Comet` contract:

```
curl -H "Content-Type: application/json" -X POST --data '{"jsonrpc":"2.0","method":"eth_call","params":[{"to": "0xc3d688B66703497DAA19211EEdff47f25384cdc3", "data": "0x0902f1ac"}, "latest"],"id":1}' http://localhost:8545
```

### Platform(s)

Linux (x86)

### What version/commit are you on?

reth Version: 0.1.0-alpha.3

### What database version are you on?

Current database version: 1

### Code of Conduct

- [X] I agree to follow the Code of Conduct

**Comment by 0xJchen** [comment]
Just find that web3js community had an ongoing PR about the duplication issue. 

https://github.com/web3/web3.js/pull/6294

**Comment by Muhammad-Altabba** [comment]
Hello guys,
Because not all RPC providers follow the specs, web3.js provided both `input` and `data`. This is for the sake of a unified user code. As it would not be optimal to cause the user to decide whether he should provide or read `data` or `input`, based on the provider he is connecting to. And this could be especially problematic for him if he used the same code to communicate with multiple providers, each at a time. 

However, web3.js ensures that `input` and `data` are identical. And if they are both given to the RPC provider but with **different** values, it throws the error: `You can\'t have "data" and "input" as properties of transactions at the same time, please use either "data" or "input" instead.`.

So, I suggest that `reth` tolerate the case, and do not throw, if both `input` and `data` are identical. And to throw only if `input` and `data` are both provided and they are also **not** identical. Or what do you think?

**Comment by 0xJchen** [comment]
> Hello guys, Because not all RPC providers follow the specs, web3.js provided both `input` and `data`. This is for the sake of a unified user code. As it would not be optimal to cause the user to decide whether he should provide or read `data` or `input`, based on the provider he is connecting to. And this could be especially problematic for him if he used the same code to communicate with multiple providers, each at a time.
> 
> However, web3.js ensures that `input` and `data` are identical. And if they are both given to the RPC provider but with **different** values, it throws the error: `You can\'t have "data" and "input" as properties of transactions at the same time, please use either "data" or "input" instead.`.
> 
> So, I suggest that `reth` tolerate the case, and do not throw, if both `input` and `data` are identical. And to throw only if `input` and `data` are both provided and they are also **not** identical. Or what do you think?
> 
> Thanks,

Thank you ser. I am switching to rust wrapper instead of web3js.

**Comment by Muhammad-Altabba** [comment]
Thanks all,
And for those who come to this issue in the future, here is the conclusion:
- The last version of `reth` ([Reth v0.1.0-alpha.5](https://github.com/paradigmxyz/reth/releases/tag/v0.1.0-alpha.5))  no more throws when facing this case. (Thanks @mattsse for making this possible at this MR: https://github.com/paradigmxyz/reth/pull/3911):
- Additionally, the next version of web3.js (v4.1.0) will not fill both `data` and `input` (done in this MR: https://github.com/web3/web3.js/pull/6294).

So, upgrading to the latest `reth` or upgrading `web3.js` to v4.1.0 once it is released, would resolve this issue.
