### ISSUE TITLE
perform js inspector on tracing task

### ISSUE THREAD

**Issue by mattsse** [paradigmxyz/reth#3951]
### Describe the feature

inspecting js tracer is currently performed in sync which is blocking

https://github.com/paradigmxyz/reth/blob/0147e5033001069f258aa1e03fa1a7166f989e4c/crates/rpc/rpc/src/debug.rs#L292-L292

it should be moved to a tracing task like:

https://github.com/paradigmxyz/reth/blob/0147e5033001069f258aa1e03fa1a7166f989e4c/crates/rpc/rpc/src/debug.rs#L246-L249

FYI @tcoratger

**Comment by tcoratger** [comment]
Will have a look!

**Comment by tcoratger** [comment]
@mattsse Are you sure that this change is desirable? I understand the purpose to migrate the execution to an async case but it looks like the sync execution was done on purpose with the mentioned comment: 

https://github.com/paradigmxyz/reth/blob/4ab924c5d361bbfdcdad9f997d16d67b4a1730b7/crates/rpc/rpc/src/debug.rs#L267-L268

With a simple migration to something like:
```rust
let mut inspector = JsInspector::new(code, config, to_db_service)?;

let (res, env, inspector) = self
  .inner
  .eth_api
  .spawn_with_call_at(call, at, overrides, move |db, env| {
      let (res, _) = inspect(db, env, &mut inspector)?;
      Ok((res, env, inspector))
  })
  .await?;

let result = inspector.json_result(res, &env)?;
Ok(GethTrace::JS(result))
```

we will get an error like:
```shell
error[E0277]: `NonNull<boa_gc::internals::gc_box::GcBox<boa_engine::script::Inner>>` cannot be sent between threads safely
   --> crates/rpc/rpc/src/debug.rs:296:26
    |
296 |                         .spawn_with_call_at(call, at, overrides, move |db, env| {
    |                          ^^^^^^^^^^^^^^^^^^ `NonNull<boa_gc::internals::gc_box::GcBox<boa_engine::script::Inner>>` cannot be sent between threads safely
```
due to the fact that `JSTracer` and all JS types are not `Send`, as mentioned in the comment, what do you think?

**Comment by mattsse** [comment]
I think it works if you move

> let mut inspector = JsInspector::new(code, config, to_db_service)?;

inside the closure
