### ISSUE TITLE
Dropped all peers after first stage loop iteration

### ISSUE THREAD

**Issue by clabby** [paradigmxyz/reth#3991]
### Describe the bug

After my node's first iteration through the stage loop, it dropped all peers and was unable to establish new connections with peers for a few hours. After around 6-7 hours, peers started connecting again, and the node successfully synced to mainnet tip.
![Screenshot 2023-07-29 at 5 03 54 PM](https://github.com/paradigmxyz/reth/assets/8406232/1edb1651-7a0f-42d2-85a5-8cf01d471f02)
![Screenshot 2023-07-29 at 5 04 10 PM](https://github.com/paradigmxyz/reth/assets/8406232/0cce9b6f-4302-47cc-8de8-2c1a21a77d05)

**Other information**:
- `reth.toml` all default values.
- Flags (RPC endpoint is not open to the internet, no logs suggesting malicious use of the admin endpoint to drop peers forcefully):
![Screenshot 2023-07-29 at 6 31 34 PM](https://github.com/paradigmxyz/reth/assets/8406232/d2958254-06b0-4716-9b8e-aa72d234197d)

### Steps to reproduce

Steps to reproduce:

1. Start syncing reth
2. After the first iteration through the stage loop, all peers drop and new peer connections could not be established for ~6h.

### Node logs

```text
n/a - Had full trace verbosity on (-vvvvv) and scanned through the logs, only relevant errors were related to `TooManyPeers` disconnections, which should be pretty standard.
```

### Platform(s)

Linux (x86)

### What version/commit are you on?

0.1.0-alpha.4

### What database version are you on?

DB Version: `1`

### If you've built Reth from source, provide the full command you used

n/a - ghcr Docker image

### Code of Conduct

- [X] I agree to follow the Code of Conduct

**Comment by bemevolent** [comment]
Another user in tg reported the same issue. My guess is an issue in the transition from the pipeline sync to the beacon sync which results in lots of incorrect `bad_message` or similar so the node bans all of its peers.

AFAICT the new `get_full_block_range()` logic doesn't actually use the `count` here https://github.com/paradigmxyz/reth/blob/b46101afb5e549d40b7b2537fff9b67e05ad4448/crates/consensus/beacon/src/engine/sync.rs#L152

So it's only requesting a single block, but thinks it's requesting a range. Bug probably follows shortly after that flow but I haven't had time to dig further. I'm sure one of the core guys can quickly pinpoint

**Comment by mattsse** [comment]
thanks @bemevolent 

we only use the count when checking the response length, assumption here is that this will never exceed the soft response limit of ~1000 headers

but we were missing proper header validation which could lead to endless penalization cycle

**Comment by bemevolent** [comment]
I rebuilt with the latest headers changes and by chance had a node that was finishing syncing tonight. This is actually a different issue. After a first pipeline cycle is complete and it's starting a second run, but still far away from the chain tip (important!). It starts requesting lots of bodies and quickly receives empty body requests and bans peers here:

https://github.com/paradigmxyz/reth/blob/8c70524fc6031dcc268fd771797f35d6229848e7/crates/net/downloaders/src/bodies/request.rs#L90-L93

I'm assuming this is because after the 1st run bodies stage, there are no block requests for at least a day where the node has the time to peer to lots of full nodes that only store 128 historical blocks. And so when it starts the second pipeline it needs lots of historical blocks again and starts requesting and then banning peers.

I'm happy to submit a fix but this goes beyond my knowledge of Ethereum p2p protocol. Should we ban full nodes until we reach the chain tip? In which case maybe there is a way to prevent peering to full nodes in the intermediate stage. Or should this just not be a reputation change for an empty response and the idea is one of the peers should have the historical block we're requesting?
