### ISSUE TITLE
Skip state root check in stage unwind command

### ISSUE THREAD

**Issue by mattsse** [paradigmxyz/reth#4114]
### Describe the feature

the stage unwind command is used to manually unwind a block range, however, if the state root check fails then it fails to unwind the block range

> `target/release/reth stage unwind num-blocks 1000 --datadir ../sepolia`
Error: Transaction error on unwind: Provider(UnwindStateRootMismatch { expected: 0x233e8325451ea76d942ced9a7745be36dec267865617ce7f3a549ddd4f3371c5, got: 0x0de48d3ce2f9ed962f0fe9a396bec2055bf43243fa78adc7b9a9903df9763d0a, block_number: 4047155, block_hash: 0xc746177d6bf617e049e52807df676265859f27d21c943ae13411214cfa0e6cab })

**Comment by alessandromazza98** [comment]
I could take this.

Just a question, should I need to create a new function that skip state root check or simply editing `take_block_and_execution_range` that is the function used? In particular this snippet of code:

```rust
// state root should be always correct as we are reverting state.
// but for sake of double verification we will check it again.
if new_state_root != parent_state_root {
    let parent_hash = self
        .block_hash(parent_number)?
        .ok_or_else(|| ProviderError::HeaderNotFound(parent_number.into()))?;
    return Err(ProviderError::UnwindStateRootMismatch {
        got: new_state_root,
        expected: parent_state_root,
        block_number: parent_number,
        block_hash: parent_hash,
    }
    .into())
}
```

My idea is to create a different function since `take_block_and_execution_range` is also used in other places and not only here.

Thanks

**Comment by mattsse** [comment]
closing since this is no longer an issue
