### ISSUE TITLE
Add blobtx sidecar to PooledTransaction

### ISSUE THREAD

**Issue by mattsse** [paradigmxyz/reth#4170]
### Describe the feature

the default txpool txs is

https://github.com/paradigmxyz/reth/blob/81e8ad4de667b1729e0fa3a16b12f0c5d373f4b5/crates/transaction-pool/src/traits.rs#L567-L572

for blob txs this also needs the blob sidecar (blobs,proofs,commitments)

this is how we currently convert TransactionSignedEcRecovered to the pool transaction:

https://github.com/paradigmxyz/reth/blob/81e8ad4de667b1729e0fa3a16b12f0c5d373f4b5/crates/primitives/src/transaction/mod.rs#L1290-L1314

the sidecar will be set from the GetPooledTransaction response:

https://github.com/paradigmxyz/reth/blob/81e8ad4de667b1729e0fa3a16b12f0c5d373f4b5/crates/net/eth-wire/src/types/transactions.rs#L70-L86

we need the sidecar in order to validate the tx

when the txs was validated we wrap it in an Arc:

https://github.com/paradigmxyz/reth/blob/81e8ad4de667b1729e0fa3a16b12f0c5d373f4b5/crates/transaction-pool/src/pool/txpool.rs#L1062-L1063

here we could `take` the sidecar out and store it in the storage backend because we don't need it anymore, we need to reattach it however when the blob tx is requested from other peers over devp2p

since it is now in an arc, we need could either add a Mutex in there, or some kind of channel sender that can communicate with the blob storage backend, which should live outside of the RwLocked txpool, so that the sidecar can be fetched on demand, when we need to convert it into the GetPooledTransaction response.

**Comment by PatStiles** [comment]
Want to take a stab at this!

**Comment by 0xprames** [comment]
the node makes the `GetPooledTransaction` req [here](https://github.com/paradigmxyz/reth/blob/84625e4a8c78637cda8e4d95f0f26d17e152522e/crates/net/network/src/transactions.rs#L343) to grab transactions that it sees its missing after recieving a `NewPooledTransactionHashes` from a peer

the response to that request as per the eip-4844 networking [spec](https://eips.ethereum.org/EIPS/eip-4844#networking) can be a blob transaction, so thats the point we'll set the blob sidecar attributes.

this occurs in the `TransactionManager` code [here](https://github.com/paradigmxyz/reth/blob/84625e4a8c78637cda8e4d95f0f26d17e152522e/crates/net/network/src/transactions.rs#L572) in `poll` when polling each of the inflight `GetPooledTransaction` requests.

so assuming we have a way to check the imported transaction if its a `BlobTransaction` or not in `import_transactions`, we'll be able to grab the blobs, proofs, and commitments and add it to the `PooledTransaction` [here](https://github.com/paradigmxyz/reth/blob/81e8ad4de667b1729e0fa3a16b12f0c5d373f4b5/crates/net/network/src/transactions.rs#L471)

need to think through the last point of splitting the sidecar from the tx [here](https://github.com/paradigmxyz/reth/blob/81e8ad4de667b1729e0fa3a16b12f0c5d373f4b5/crates/transaction-pool/src/pool/txpool.rs#L1063), but using a channel sender between wherever the blob storage backend is running and fetching it on-demand when [responding](https://github.com/paradigmxyz/reth/blob/81e8ad4de667b1729e0fa3a16b12f0c5d373f4b5/crates/net/network/src/transactions.rs#L181) to a `GetPooledTransaction` request makes sense.

@mattsse @PatStiles   ^ let me know if that aligns with what you were thinking as well

I commented this in the PR but i think [this](https://github.com/paradigmxyz/reth/pull/4172) makes sense to get in/rebase off off for this issue, since apparently the arbitary encoding for `BlobTransactions` is incorrect (?) and the `GetPooledTransactions` response moveds to a `PooledTransactionResponse` enum type to differentiate between eip-4844/non-eip4844 txs

**Comment by Rjected** [comment]
Should have been fixed in #4267
