### ISSUE TITLE
Allow multiple arguments on `--trusted-peers`, separated by comma

### ISSUE THREAD

**Issue by geomad** [paradigmxyz/reth#4615]
### Describe the feature

Right now to add multiple trusted peers the user should use `--trusted-peers` multiple times like so:
`--trusted-peers enode://xxx --trusted-peers enode://yyy`

Allowing multiple arguments to the parameter would look cleaner and clear confusion eg:
 `--trusted-peers enode://xxx,enode://yyy`

**Comment by tcoratger** [comment]
It seems already possible since `trusted_peers` is defined as a `vec` no?

https://github.com/paradigmxyz/reth/blob/357301cc29536096553fd0284591a85d2ee39622/bin/reth/src/args/network_args.rs#L20-L23

Furthermore, I admit that it is not currently super clear in the documentation but it seems possible. For me, to isolate a single trusted peer, this cli command should be used:

https://github.com/paradigmxyz/reth/blob/357301cc29536096553fd0284591a85d2ee39622/bin/reth/src/p2p/mod.rs#L65-L67

What do you think @mattsse?
