### ISSUE TITLE
Support EIP-4844 transaction when building pending block

### ISSUE THREAD

**Issue by mattsse** [paradigmxyz/reth#4673]
### Describe the feature

https://github.com/paradigmxyz/reth/blob/449a9c002369db892a552e8d0ba3a2424866e5ad/crates/rpc/rpc/src/eth/api/pending_block.rs#L28-L37

## TODO

keep track of max blob space
set eip4844 header fields correctly
apply pre_block_beacon_root_contract_call 

see also 

https://github.com/paradigmxyz/reth/blob/449a9c002369db892a552e8d0ba3a2424866e5ad/crates/payload/basic/src/lib.rs#L634-L641

**Comment by alessandromazza98** [comment]
I could take it

**Comment by mattsse** [comment]
sweet,

quick node here, most of the code could be unified with the default block builder fn but they have slightly different args etc so for now it's fine to duplicate

**Comment by alessandromazza98** [comment]
A question:

Do I have to rewrite `pre_block_beacon_root_contract_call` function inside `pending_blocks.rs` file or should I import it from `reth-basic-payload-builder`? The easiest I think could be rewrite the function otherwise I have to make `pub` some structs and fields and also convert some errors.

Thanks in advance
