### ISSUE TITLE
Implement missing logics in `on_command` function for `TransactionsManager`

### ISSUE THREAD

**Issue by tcoratger** [paradigmxyz/reth#4691]
### Describe the feature

This issue is created to track the implementation of missing logic in the `TransactionsManager`'s `on_command` function in the project. The `on_command` function is responsible for handling various commands related to transaction management, and there are several functionalities that need to be implemented.

https://github.com/paradigmxyz/reth/blob/6016da7a1234de70afb3b6d796909504faeb1627/crates/net/network/src/transactions.rs#L428-L437

The missing logic to be added includes handling commands to propagate transaction hashes, get active peers, propagate transactions to specific peers, get transaction hashes, and get peer transaction hashes. Implementing these functionalities will enhance the overall capabilities of the `TransactionsManager` module.

**Comment by SleepingShell** [comment]
I would like to attempt implementing some of these. I've worked on PropagateTransactionsTo, am I correct this should have the same logic as this? https://github.com/paradigmxyz/reth/blob/675c6bfc390b17d274541ef251375741f48dd3c3/crates/net/network/src/transactions.rs#L266

**Comment by SleepingShell** [comment]
@mattsse , I have added implementations of getting the peer's hashes and active peers to https://github.com/paradigmxyz/reth/pull/4772 .

Please confirm that this functionality is to get the known tx hashes from the LRU cache. Since there is no eth message for requesting new transaction hashes, I am going to assume that this is the desired functionality.

Additionally, I don't see where this output is consumed?
