### ISSUE TITLE
Move trace_block_with and trace_block_until to EthTransactions trait

### ISSUE THREAD

**Issue by mattsse** [paradigmxyz/reth#5002]
### Describe the feature

Move the implementations of 
https://github.com/paradigmxyz/reth/blob/27a0a06ca44e9ee25f05abfbad8276c518a33eff/crates/rpc/rpc/src/trace.rs#L358-L358

and trace_block_until introduced in #4974

to https://github.com/paradigmxyz/reth/blob/27a0a06ca44e9ee25f05abfbad8276c518a33eff/crates/rpc/rpc/src/eth/api/transactions.rs#L52-L52

## TODO
* define trait functions
* move impl from trace.rs to EthTransactions impl

fyi @smatthewenglish

**Comment by yash-atreya** [comment]
I can take this

**Comment by DoTheBestToGetTheBest** [comment]
i take this if possible

**Comment by DoTheBestToGetTheBest** [comment]
@yash-atreya hey if you are always okay to take this, i leave it :)

**Comment by tcoratger** [comment]
@mattsse Here, in order to handle:

https://github.com/paradigmxyz/reth/blob/27a0a06ca44e9ee25f05abfbad8276c518a33eff/crates/rpc/rpc/src/trace.rs#L378-L379 

directly in the `EthTransactions` trait, we have to pass a `TraceApi<Provider, Eth>` additionnal argument to the function `trace_block_with` which will now be directly in the trait no?

**Comment by mattsse** [comment]
hmm, I don't think so, because block_id is already an argument and these two functions are available on `EthApi`

https://github.com/paradigmxyz/reth/blob/920e3f0b88f0577b127ffb39165d1644632dadbf/crates/rpc/rpc/src/eth/api/transactions.rs#L242-L243
