### ISSUE TITLE
Use `block_with_senders` in EthStateCache

### ISSUE THREAD

**Issue by mattsse** [paradigmxyz/reth#5090]
### Describe the feature

requesting full blocks(eth_getBlockByHash(true)) requires sender recovery, which is currently a bottleneck in rpc, we can read the senders from disk via `BlockWithSenders`

There's an argument for only reading or recovering Senders lazily in the cache, but I think doing an additional batch read for senders when fetching the block should be fine. however we only really need this for the `getBlock(full)` requests, so doing this lazily would probably be the most efficient solution, considering that we can already cache new blocks with recovered transactions.
But since this is a lot more complex, let's start with always reading senders.

## TODO
* cache Block with Sender instead of `Block`
https://github.com/paradigmxyz/reth/blob/d3de32a9dc57958b64a6d80d9a52224f9b773858/crates/rpc/rpc/src/eth/cache/mod.rs#L46-L46
* update all the channel types accordingly
* add a new request function to the cache returns BlockWithSenders and use this for `eth_getBlock(full)` requests.
* The existing convert function needs to updated as well, which could become a bit messy
https://github.com/paradigmxyz/reth/blob/d3de32a9dc57958b64a6d80d9a52224f9b773858/crates/rpc/rpc-types-compat/src/block.rs#L12-L24

I wonder if we should add a new block helper type first where the transactions are the new `TransactionSignedVariant` instead: https://github.com/paradigmxyz/reth/pull/5098

@tcoratger maybe this sounds interesting?

**Comment by tcoratger** [comment]
@mattsse I think I understand the logic, the goal is to not need to fetch the senders a posteriori and therefore to use the `BlockWithSenders` structure which already provides a vector with the addresses of the senders.

If I'm not mistaken, this means that all types of `crates/rpc/rpc/src/eth/cache/mod.rs` which were before `Block` must be replaced by `BlockWithSenders` and all those which were `SealedBlock` should be replaced by `SealedBlockWithSenders` is this correct?

For example, the function below:

https://github.com/paradigmxyz/reth/blob/d3de32a9dc57958b64a6d80d9a52224f9b773858/crates/rpc/rpc/src/eth/cache/mod.rs#L181-L191

was until now returning a type `RethResult<Option<(SealedBlock, Vec<Receipt>)>>` and it must now return a type `RethResult<Option<(SealedBlockWithSenders, Vec<Receipt>)>>`, is this correct or is my approach wrong?

Because for me if we make the first switch from `Block` to `BlockWithSenders` in the `BlockLruCache` type then we have to make the switch everywhere right?

**Comment by mattsse** [comment]
> the goal is to not need to fetch the senders a posterior 

we currently need to recover the senders everytime we're serving a full block requests, with ~200 txs this can take a bit

> which were before Block must be replaced by BlockWithSenders and all those which were SealedBlock should be replaced by SealedBlockWithSenders is this correct?

I don't think this is necessary, I'd like to keep all API functions of the cache as is, but add another that also returns the senders, because we only really need this for the full block response.

> Because for me if we make the first switch from Block to BlockWithSenders in the BlockLruCache type then we have to make the switch everywhere right?

hmm, I don't think this is true, because if you look at the type:

https://github.com/paradigmxyz/reth/blob/9dd270e4e8095a4cab1d2118f8f965eec68f4db7/crates/primitives/src/block.rs#L85-L92

this just wraps the block and has all the transaction senders.

so this command for example

https://github.com/paradigmxyz/reth/blob/9dd270e4e8095a4cab1d2118f8f965eec68f4db7/crates/rpc/rpc/src/eth/cache/mod.rs#L315-L320

can be serviced by cloning the wrapped block

then we can add another cache command that can serve BlockWithSenders like
`GetBlockWithSenders` or `GetBlockTransactionsRecovered`
https://github.com/paradigmxyz/reth/blob/9dd270e4e8095a4cab1d2118f8f965eec68f4db7/crates/rpc/rpc/src/eth/cache/mod.rs#L456-L456

**Comment by mattsse** [comment]
I realize, this would also improve a few tracing endpoints that are replaying blocks or block transactions

**Comment by mattsse** [comment]
@tcoratger just checking in, are you on this or can this be claimed?

**Comment by tcoratger** [comment]
> @tcoratger just checking in, are you on this or can this be claimed?

@mattsse Sorry I didn't update, I have a lot of other things to do, if anyone wants to take it he can :)

**Comment by supernovahs** [comment]
I can take this

**Comment by supernovahs** [comment]
We want `getBlock` and `getBlockWithSenders` both as separate variants right?
