### ISSUE TITLE
Implement `Stream` for `Discovery`

### ISSUE THREAD

**Issue by Rjected** [paradigmxyz/reth#5128]
### Describe the feature

Currently discovery has a useful `poll` method which is used inside the `StateManager`:
https://github.com/paradigmxyz/reth/blob/9dd270e4e8095a4cab1d2118f8f965eec68f4db7/crates/net/network/src/state.rs#L399-L401

The method is implemented here:
https://github.com/paradigmxyz/reth/blob/9dd270e4e8095a4cab1d2118f8f965eec68f4db7/crates/net/network/src/discovery.rs#L190-L216

`Discovery` is useful because it can spawn both a `Discv4Service` and `DnsDiscoveryService`, and the poll method adds dnsdisc updates to discv4. This means consumers don't need to manage the updates for both services, they can instead just consume updates from `Discovery`.

The `poll` method is very similar to what would need to be implemented for `Stream`, so the trait should be implemented for `Discovery`.

**Comment by rodrigoherrerai** [comment]
Can I take it ?

**Comment by mattsse** [comment]
I think this can be useful if you want to use the Discovery as a standalone component, but is not required internally, because would introduce an `Option` wrapper.

but stream would come with a lot more util functions, so supportive

so the stream impl should just map the return of the existing poll, maybe we rename this  then.
