### ISSUE TITLE
Allowing some rpc restrictions to be lifted up with ="max" args

### ISSUE THREAD

**Issue by kaliubuntu0206** [paradigmxyz/reth#5278]
### Describe the change

After reading https://blog.merkle.io/blog/run-a-reth-node some people lift up default restrictions since they run their own loadbalancers to restrict public requests.

Would be great to support some `"max"` style args for other restriction flags like this PR

https://github.com/paradigmxyz/reth/commit/0449c5eca6e4a9d0e15cc8700e457425629838c0#diff-e488c1982272a23faac85301fe3e41d24bdd27539df3526fb1ae634476b70d05R4

**Comment by mattsse** [comment]
which ones specifically?

I think we should also support "max" value

**Comment by kaliubuntu0206** [comment]
@mattsse Means that we should change the previous commit as well?

**Comment by mattsse** [comment]
yeah, I'm leaning towards that actually, treating 0 as max just feels wrong.

**Comment by kaliubuntu0206** [comment]
Sure, why not? Just hoping that it wouldn't confuse users with Geth but with a proper documentation I think it is good

**Comment by mattsse** [comment]
good point, I'm not sure where geth treats 0 as max, but most of these values are only reth specific.

since we have a few different types like u32,u64,usize, we likely want a generic solution for the wrapper type, unfortunately there's no std solution to get the max value of a type so we need to find another way, I guess a simple helper trait would do it

**Comment by mattsse** [comment]
we have this now
