### ISSUE TITLE
Use already recovered transaction during tracing

### ISSUE THREAD

**Issue by mattsse** [paradigmxyz/reth#5497]
### Describe the feature

with #5302

we're caching the senders of transactions, so we no longer need to recover them during tracing

## TODO

use SealedBlockWithSenders during block level tracing

**Comment by yash-atreya** [comment]
Can take this !

**Comment by mattsse** [comment]
sweet!, lmk if you need pointers, this affects trace_ debug_ rpc calls that fetch the full blocks

**Comment by gakonst** [comment]
@yash-atreya do let us know when you intend to take it on ^^

**Comment by yash-atreya** [comment]
Hey @gakonst @mattsse 

I was going to start working on this on Thursday. 

Do you intend to include this in alpha.11? Will try to do it sooner then.

**Comment by mattsse** [comment]
thursday's fine :) 

thanks in advance 🙏

**Comment by yash-atreya** [comment]
Hey @mattsse 

Extremely sorry for the delay. 

Needed some guidance to implement this. I have identified the block level tracing methods where the cached senders should be used instead of recovering the signers.

1. ```trace_block```
Under the hood this function uses ```fn trace_block_until``` to generate the traces.
https://github.com/paradigmxyz/reth/blob/025511baa654bf664c3d3e684364707bc6db5ed2/crates/rpc/rpc/src/eth/api/transactions.rs#L762
```trace_block_until``` calls ```self.block_by_id``` to get the ```SealedBlock```
https://github.com/paradigmxyz/reth/blob/025511baa654bf664c3d3e684364707bc6db5ed2/crates/rpc/rpc/src/eth/api/transactions.rs#L781-L782
**Enhancement:**
Use ```self.block_with_senders(blockId)``` which returns ```SealedBlockWithSenders```. This removes the need doing the following 
https://github.com/paradigmxyz/reth/blob/025511baa654bf664c3d3e684364707bc6db5ed2/crates/rpc/rpc/src/eth/api/transactions.rs#L808 instead we can just do:
```rust
let tx = TransactionSignedEcRecovered::from_signed_transaction(tx, signer); // Signer is from block.senders[idx]
``` 
2. ```trace_filter```
The above enhancement will also apply here as this function also uses ```trace_block_until```.
Moreover, this function fetches blocks in the specified range:
https://github.com/paradigmxyz/reth/blob/025511baa654bf664c3d3e684364707bc6db5ed2/crates/rpc/rpc/src/trace.rs#L260
And the signers of the fetched blocks are recovered and used in the match filter, like so:
https://github.com/paradigmxyz/reth/blob/025511baa654bf664c3d3e684364707bc6db5ed2/crates/rpc/rpc/src/trace.rs#L267-L275
**Enhancement:**
Add new method ```fn block_range_with_senders``` which fetches the range of block and returns ```ProviderResult<Vec<BlockWithSenders>>```. We do not need to recover the signers now. However this uses the db and not the cache.

3. ```replay_block_transactions```
This method also uses ```trace_block_until``` under the hood and the initial enhancement applies here as well.

I hope I'm on the right track, would appreciate your input on this.

**Comment by mattsse** [comment]
@yash-atreya sorry I forgot to respond to this one here.
your PR was great, so now we can the same thing for:

https://github.com/paradigmxyz/reth/blob/main/crates/rpc/rpc/src/eth/api/call.rs#L74-L74

and all the others that fetch blocks for tracing

**Comment by yash-atreya** [comment]
> @yash-atreya sorry I forgot to respond to this one here. your PR was great, so now we can the same thing for:
> 
> https://github.com/paradigmxyz/reth/blob/main/crates/rpc/rpc/src/eth/api/call.rs#L74-L74
> 
> and all the others that fetch blocks for tracing

@mattsse Thanks. I'll get on it.

Just wanted to confirm whether I should move forward with the following enhancement I suggested for `trace_filter`, which uses the db instead of the cache to retrieve the block range with senders. I'll create a separate PR for this.
> Enhancement:
Add new method fn block_range_with_senders which fetches the range of block and returns ProviderResult<Vec<BlockWithSenders>>. We do not need to recover the signers now. However, this uses the db and not the cache.

**Comment by mattsse** [comment]
> Just wanted to confirm whether I should move forward with the following enhancement I suggested for trace_filter, which uses the db instead of the cache to retrieve the block range with senders. I'll create a separate PR for this.

need to think about it, but I believe we want this yes

**Comment by yash-atreya** [comment]
> > Just wanted to confirm whether I should move forward with the following enhancement I suggested for trace_filter, which uses the db instead of the cache to retrieve the block range with senders. I'll create a separate PR for this.
> 
> need to think about it, but I believe we want this yes

Have created the PR in case you need it. #5647

**Comment by yash-atreya** [comment]
Hey @mattsse, the last few PRs have been extremely fun, thank you for your guidance. 
Feel free to assign me more issues, I'll be on the lookout as well.

**Comment by mattsse** [comment]
ty!
if you don't find any interesting issue please ping dm on tg or twitter and I'll come up if something
