### ISSUE TITLE
Support custom component types via CLI extension

### ISSUE THREAD

**Issue by mattsse** [paradigmxyz/reth#5501]
### Describe the feature

currently the CLI extension is limited to consuming `RethComponents` which includes the regular txpool.

Ideally we support embedding custom txpool types (and eventually more, like CL Payload, etc..) via the extension trait.

this needs to be plugged into the `RethNodeCommandConfig`.

I think we another trait that defines types 

like 

```rust
trait RethComponents {
  TxPool: ....,
  Payload: ....,
  ....
}
```

then `RethNodeCommandConfig` becomes `RethNodeCommandConfig<T: RethComponents>`

and we it as another associated type to:

https://github.com/paradigmxyz/reth/blob/b93b909edeee439cdafab2adf77a060b3b4e8b53/bin/reth/src/cli/ext.rs#L25-L25

I kinda expected this to some degree, because we were already using the `RethCliExt` trait which only has a single associated type

we then can do something like:

```rust
pub trait RethCliExt {

    type Node: RethNodeCommandExt<Self::Components>;
    
    type Components: RethComponents;
}

trait RethComponents {
  type Txpool: TransactionPool + ...;

} 
```

naming TBD.

**Comment by loocapro** [comment]
Hi @mattsse I can take this.

**Comment by mattsse** [comment]
I think this is the direction we want to go with, so I appreciate if you could start drafting the RethComponents trait.

**Comment by Rjected** [comment]
Thought about this for a bit, and had a few notes, lmk if this makes sense:
* If we have a custom `Payload` type, then it seems like we would need an abstraction that the `PayloadBuilderHandle` would implement. Otherwise `PayloadBuilderHandle` would still return the concrete `BuiltPayload` type instead of the custom type. Maybe instead the custom type should just be a `PayloadBuilder` trait, which has an associated `Payload` type.
* Would it even make sense to `impl RethNodeCommandConfig<T> for Struct`, for multiple `T` types? If not then an associated type seems more appropriate
