### ISSUE TITLE
Increase `session_command_buffer` size

### ISSUE THREAD

**Issue by jonasbostoen** [paradigmxyz/reth#575]
### Describe the feature

After running `reth` for a while and interacting with transactions, I start to run into receive errors on the `GetPooledTransactions` message, where the response is supposed to be sent on the oneshot `response` channel. The receive error means that the sender is dropped, which I think can only be because we're using `try_send` on the `commands_to_session` buffered channel, which can silently fail if the buffer is full: https://github.com/paradigmxyz/reth/blob/c070e77524680e0937ab4b2131452d8d5dbe80e4/crates/net/network/src/session/mod.rs#L243

The buffer size is set here and is 10 by default:
https://github.com/paradigmxyz/reth/blob/c117d4b44f63de8821160510cf9d492be9dc25b6/crates/net/network/src/session/config.rs#L23-L38

The fix should just be increasing the buffer size, I can do a PR for that, but would like to have some feedback on how big it should be. We should also probably introduce some trace logs that print the current buffer size when sending a message to the session.

**Comment by mattsse** [comment]
ty for this feedback.

these were basically just initial assumptions.

Since we also send eth messages through here, increasing is reasonable.

This buffer basically just handles egress, `10` was very conservative, we can bump it to 32 first and increase again.

This is a per session buffer so 32 should be fine.

>  I can do a PR for that,

🙏
