### ISSUE TITLE
Reth panicked with "body indices for block X must exist"

### ISSUE THREAD

**Issue by tobernguyen** [paradigmxyz/reth#5829]
### Describe the bug

Reth crashed. These are the logs before it exited.

```
2023-12-16T16:51:25.472382Z  INFO reth::cli: Status connected_peers=80 freelist=3716307 latest_block=18799847
thread 'tokio-runtime-worker' panicked at /project/crates/storage/provider/src/bundle_state/bundle_state_with_receipts.rs:377:25:
body indices for block 18799925 must exist. last available block number: Some(18799924)
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
2023-12-16T16:51:50.089843Z ERROR reth_tasks: Critical task `consensus engine` panicked: `body indices for block 18799925 must exist. last available block number: Some(18799924)`
2023-12-16T16:51:50.097081Z  INFO reth::cli: Wrote network peers to file peers_file="/reth/known-peers.json"
Error: Critical task `consensus engine` panicked: `body indices for block 18799925 must exist. last available block number: Some(18799924)`
Location:
    /rustc/79e9716c980570bfd1f666e3b16ac583f0168962/library/core/src/convert/mod.rs:716:9
```

### Steps to reproduce

I don't know how to reproduce it.

### Node logs

[reth-crash-2023-12-19.txt](https://github.com/paradigmxyz/reth/files/13720450/reth-crash-2023-12-19.txt)

### What version/commit are you on?

0.1.0-alpha.13

### What database version are you on?

Current database version: 1

### What type of node are you running?

None

### Code of Conduct

- [X] I agree to follow the Code of Conduct

**Comment by tobernguyen** [comment]
This has occurred again and I have captured debug logs this time. I have 2 nodes that crashed due to the same error but for different blocks. I attached both debug logs.

[reth-crash-2023-01-01.log.zip](https://github.com/paradigmxyz/reth/files/13806238/reth-crash-2023-01-01.log.zip)
[reth-crash-2023-01-01b.log.zip](https://github.com/paradigmxyz/reth/files/13806243/reth-crash-2023-01-01b.log.zip)

**Comment by rakita** [comment]
This is related to the receipts in blockchain tree. 

It's not relevant but it seems the block commit time is around 9s.

But the problem seems to be around this: https://github.com/paradigmxyz/reth/blob/8dff31e3accf63521f746dc797ce0c3da2ea86bf/crates/blockchain-tree/src/chain.rs#L159-L178

We are reverting the tip of the side chain that we want to fork, and that is okay, and after it we extend reverted state we new state change. Problem is we are not discarding receipt from chain that we want to fork and they stay in two places.

in essence we are doing something like:
```rust
let mut state = self.state().clone();
state.revert_to(parent.number);
let block_state = .... execute new_block and get new state ...
state.extend(block_state);
```

What we should add before last extend is `remove_all_receipts` this would remove all receipts that belong to the original chain.

**Comment by rakita** [comment]
fixed in https://github.com/paradigmxyz/reth/pull/5921
