### ISSUE TITLE
Base: trace_call returns internal blocking task error

### ISSUE THREAD

**Issue by quickchase** [paradigmxyz/reth#6008]
### Describe the bug

When trying to test `trace_call` and `trace_callMany` on Base Mainnet and Base Sepolia we get back the error `internal blocking task error`

### Steps to reproduce

Run op-reth on Base Mainnet or Base Sepolia - try to use trace_call or trace_callMany

Here's a sample payload for base-sepolia

```json
{
  "jsonrpc": "2.0",
  "id": 1,
  "method": "trace_call",
  "params": [
    {
      "from": "0xd8ea779b8ffc1096ca422d40588c4c0641709890",
      "to": "0xa94f5374fce5edbc8e2a8697c15331677e6ebf0b",
      "value": "0x186a0"
    },
    [
      "trace"
    ]
  ]
}
```

### Node logs

```text
I think these logs are related:


op-reth[4231]: thread '<unnamed>' panicked at /root/.cargo/git/checkouts/revm-bf744d8ffabcbad9/b00ebab/crates/revm/src/evm_impl.rs:267:17:
op-reth[4231]: [OPTIMISM] Failed to load enveloped transaction.
op-reth[4231]: stack backtrace:
op-reth[4231]:    0: rust_begin_unwind
op-reth[4231]:              at /rustc/82e1608dfa6e0b5569232559e3d385fea5a93112/library/std/src/panicking.rs:645:5
op-reth[4231]:    1: core::panicking::panic_fmt
op-reth[4231]:              at /rustc/82e1608dfa6e0b5569232559e3d385fea5a93112/library/core/src/panicking.rs:72:14
op-reth[4231]:    2: revm::evm_impl::EVMImpl<GSPEC,DB>::transact_preverified_inner
op-reth[4231]:    3: <revm::evm_impl::EVMImpl<GSPEC,DB> as revm::evm_impl::Transact<<DB as revm_primitives::db::Database>::Error>>::transact
op-reth[4231]:    4: revm::evm::EVM<DB>::inspect
op-reth[4231]:    5: reth_rpc::eth::revm_utils::inspect_and_return_db
op-reth[4231]:    6: <rayon_core::job::HeapJob<BODY> as rayon_core::job::Job>::execute
op-reth[4231]:    7: rayon_core::registry::WorkerThread::wait_until_cold
op-reth[4231]: note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

### Platform(s)

Linux (x86)

### What version/commit are you on?

0.1.0-alpha.14

### What type of node are you running?

Archive (default)

### If you've built Reth from source, provide the full command you used

export RUSTFLAGS="-C target-cpu=native"; cargo build --bin op-reth --profile maxperf --features "optimism,jemalloc"

### Code of Conduct

- [X] I agree to follow the Code of Conduct

**Comment by quickchase** [comment]
Possibly related: #5514

**Comment by quickchase** [comment]
Also, your docs are missing a `]` at the end of this example:

![image](https://github.com/paradigmxyz/reth/assets/87909910/e26239cb-3bcd-44b0-b333-e4d6229b5884)

**Comment by mattsse** [comment]
@clabby @refcell 

I assume this is an issue with how we configure the revm's TxEnv for calls on Optimism:

https://github.com/paradigmxyz/reth/blob/df4774c709c906976842425f294f5e3f8fe876df/crates/rpc/rpc/src/eth/revm_utils.rs#L334-L335

which will cause a panic due to missing tx envelope bytes: https://github.com/bluealloy/revm/issues/967

this is a massive config footgun.

What should be set for Calls? Was unable to navigate op-geth and find the solution

**Comment by Rjected** [comment]
It looks op-geth uses this `RollupCostData` struct instead of putting the entire enveloped transaction in the env.

`RollupCostData`:
https://github.com/ethereum-optimism/op-geth/blob/a79bde2c0f4f11620a0a7b1cd81d4274d6099e83/core/types/rollup_cost.go#L79-L84

This is also the argument to their equivalent of `calculate_tx_l1_cost`: 
https://github.com/ethereum-optimism/op-geth/blob/a79bde2c0f4f11620a0a7b1cd81d4274d6099e83/core/types/rollup_cost.go#L91

I can't find the cost data being set in the op-geth `eth_call` path though, so it's possible it is just unset and taking default values (0, 0).

**Comment by upnodedev** [comment]
This cause our op-proposer to fail
