### ISSUE TITLE
Doc generation fails when using reth as a dependency 

### ISSUE THREAD

**Issue by 0xvanbeethoven** [paradigmxyz/reth#6030]
### Describe the bug

I encountered multiple errors while trying to generate documentation for my workspace when using reth crates as a dependency. These errors seem to be related to unresolved imports, missing types, and issues with custom attributes.

**To Reproduce:**

**Error Logs:**
Here are the error logs I encountered:

1. Custom attribute panicked in `pipeline/mod.rs` and `txpool.rs`:
  
 ```
error: custom attribute panicked
  --> /Users/user/.cargo/git/checkouts/reth-36d3ea1d1152b20c/43cdd73/crates/stages/src/pipeline/mod.rs:41:17
        |
   41 | #[cfg_attr(doc, aquamarine::aquamarine)]
       |                 ^^^^^^^^^^^^^^^^^^^^^^
       |
       = help: message: Unable to read mermaid file: Os { code: 2, kind: NotFound, message: "No such file or directory" }
 ```

2. Unresolved imports and missing types in various modules:
```
   error[E0432]: unresolved import `crate::Pipeline`
   ...
   error[E0412]: cannot find type `Pipeline` in this scope
   ...
   error[E0432]: unresolved import `crate::pool::txpool::TxPool`
   ...
   error[E0412]: cannot find type `TxPool` in this scope
   ...
```

See screenshots:

<img width="1526" alt="Screenshot 2024-01-11 at 18 26 03" src="https://github.com/paradigmxyz/reth/assets/103021596/0ea660d0-7444-4d30-a229-4a954f6e57f1">

<img width="2254" alt="Screenshot 2024-01-11 at 18 26 57" src="https://github.com/paradigmxyz/reth/assets/103021596/6f8ae9ed-5866-4287-9c54-8553bd0337f8">

### Steps to reproduce

1. Import reth crates as dependancies specifically `reth-transaction-pool`
2. Run `cargo doc` to generate documentation.
3. See error.

### Platform(s)

Mac (Apple Silicon)

### What version/commit are you on?

rev = "43cdd73" 

### What type of node are you running?

None

### Code of Conduct

- [X] I agree to follow the Code of Conduct

**Comment by Rjected** [comment]
I figured out why this happens:
* We currently have docs in the `reth/docs/mermaid/` directory

**When `cargo doc` runs in the reth workspace:**

(ie, locally checked out rust project)
* Paths are relative to the workspace root. So `include_mmd!(docs/mermaid/txpool.mmd)` works.


**When `cargo doc` (and the aquamarine proc macro) runs in another project with `reth-transaction-pool` as a dependency:**

This is run in the `CARGO_MANIFEST_DIR` for the `reth-transaction-pool` crate. For example `/Users/dan/.cargo/git/checkouts/reth-36d3ea1d1152b20c/c12e5f7/crates/transaction-pool`. In this situation, aquamarine searches for `CARGO_MANIFEST_DIR/docs/mermaid/txpool.mmd`.

This is problematic because:
* Let's say we put mermaid files in `reth/crates/transaction-pool/docs/mermaid/`, and reference as `include_mmd!(docs/mermaid/txpool.mmd)`. When developing (in the reth workspace), this would attempt to load relative to the workspace root, not the transaction-pool root. So we would get the same failures.
* If we don't change the location of the mermaid diagrams, projects that use reth crates as a dependency will fail `cargo doc`.

I think this is a bug in aquamarine - it should always prepend `CARGO_MANIFEST_DIR` to the path.
