### ISSUE TITLE
Refactor unused Executor

### ISSUE THREAD

**Issue by rkrasiuk** [paradigmxyz/reth#627]
[`Executor` struct](https://github.com/paradigmxyz/reth/blob/main/crates/executor/src/executor.rs#L21-L24) and [`BlockExecutor` trait](https://github.com/paradigmxyz/reth/blob/main/crates/interfaces/src/executor.rs#L5-L12) are currently not used anywhere. Refactor executor functions  to implement `BlockExecutor`

cc @rakita

**Comment by Genysys** [comment]
would love to take this on

**Comment by rakita** [comment]
I would love to have standalone function for execution but implement `BlockExecutor` trait on `Executor` that would call it

**Comment by rkrasiuk** [comment]
Would be nice to hide revm internals from the consumer of the executor. Ref https://github.com/paradigmxyz/reth/pull/631#discussion_r1058496119

**Comment by jinsankim** [comment]
@Genysys If you don't mind, I'd like to take this one. I ask you because it looks like not progressing and also I'm interested in it.

**Comment by jinsankim** [comment]
https://github.com/paradigmxyz/reth/blob/f771e23f9a3e4238bb413a55f02d1536126a0ea1/crates/stages/src/stages/execution.rs#L132-L133

I think it's impossible to meet the both condition, 'using standalone function' and 'hiding revm internals'. With above 'stages/execution.rs', in order to keep the behavior, we need to hold the `SubState`(CacheDB) during iteration.  So I think there are two available approaches:

1. Use `Executor` instance. `Executor` instance could hold a `SubState`(CacheDB).
2. Just rename it to something more descriptive as @gakonst said.

HDYT?

**Comment by jinsankim** [comment]
How about removing `BlockExecutor` trait but just keeping only `Executor` struct.

The problem I faced:

* In `reth-interface`, `BlockExecutor.execute()` might return `Result<ExecutionResult, Error>`.
* `ExecutionResult` is defined in `reth-executor`.

HDYT?
