### ISSUE TITLE
Add `BeaconHeader` structure

### ISSUE THREAD

**Issue by tcoratger** [paradigmxyz/reth#6294]
### Describe the feature

As per the Ethereum consensus specification ([Beacon Chain](https://github.com/ethereum/consensus-specs/blob/dev/specs/phase0/beacon-chain.md#beaconblockheader)) and demonstrated in the Geth implementation ([header type](https://github.com/ethereum/go-ethereum/blob/eaac53ec383342fa6ef9c333659d40f7c5dac108/beacon/types/header.go#L43-L58)), it should be reasonable to introduce a new `BeaconHeader` structure in the codebase.

### Proposed `BeaconHeader` Structure:

```rust
struct BeaconBlockHeader {
    slot: Slot,
    proposer_index: ValidatorIndex,
    parent_root: Root,
    state_root: Root,
    body_root: Root,
}
```

This structure defines a beacon header with the specified fields, aligning with the Ethereum consensus specification.

**Comment by Rjected** [comment]
We probably should not add this type into reth, it is only in the geth codebase because geth has an implementation of a beacon consensus light client, which we do not have plans of adding. This also exists in [`ethereum-consensus`](https://github.com/ralexstokes/ethereum-consensus/blob/main/ethereum-consensus/src/phase0/beacon_block.rs) and [`lighthouse`](https://github.com/sigp/lighthouse/tree/stable/consensus/types/src). If another rust application does not find these types sufficient, maybe we can consider adding this to alloy.
