### ISSUE TITLE
Support for Blast Sepolia

### ISSUE THREAD

**Issue by CruzMolina** [paradigmxyz/reth#6525]
### Describe the feature

Can you add `blast_sepolia` to the list of built in supported chains?

**Comment by mattsse** [comment]
it is not supported.

In order to support blast we'd need a few more changes, most notably the account model needs to be different. Currently account types are fixed, though we're working on making parts of the chain more configurable, but no specific plans for the account yet.

I'm closing this because there are currently no plans for this
