### ISSUE TITLE
validate tx in mempool in parallel

### ISSUE THREAD

**Issue by justcode740** [paradigmxyz/reth#6557]
### Describe the feature

during my work on https://github.com/paradigmxyz/reth/pull/6546, i find the tx validation here https://github.com/paradigmxyz/reth/blob/cd0a2f34bcdd0e4ce86c915d3299848c3ba18ac7/crates/transaction-pool/src/validate/eth.rs#L60 is done in serial but it feels like a trivially parallelizable task, @emhane asks me to open an issue to ask for more opinion, if there might be some performance gain, i can open a pr on this.

**Comment by mattsse** [comment]
under the hood they are already parallelized via a validation task

currently, we're using 2, but we should actually consider bumping this

https://github.com/paradigmxyz/reth/blob/d7a2123181df49ffda4ff497d6b7fb66e55dc822/crates/transaction-pool/src/validate/task.rs#L48-L54

closing this because we already have a way to parallelize these
