### ISSUE TITLE
Improve test coverage of set_capability_offsets

### ISSUE THREAD

**Issue by mattsse** [paradigmxyz/reth#656]
### Describe the feature

https://github.com/paradigmxyz/reth/blob/ebd686a40742ad983fb0d3516adc7ba95b6744e4/crates/net/eth-wire/src/p2pstream.rs#L496-L499

not sure if applicable here, but there is [HashSet::intersection](https://doc.rust-lang.org/std/collections/hash_set/struct.HashSet.html#method.intersection)

**Comment by gakonst** [comment]
@akirillo PTAL at this! 

@mattsse @Rjected do we have some test vectors we could use here?

**Comment by akirillo** [comment]
looking into this, taking some time to gather context on capabilities / offsets & the implementation here

**Comment by Rjected** [comment]
> @Rjected do we have some test vectors we could use here? I would also be open to a complete rewrite of the function

There are some [geth test vectors](https://github.com/ethereum/go-ethereum/blob/5f70f9fd37b14c6c8021cd277f9d620dbef7583b/p2p/peer_test.go#L269) for testing [`matchProtocols`](https://github.com/ethereum/go-ethereum/blob/5f70f9fd37b14c6c8021cd277f9d620dbef7583b/p2p/peer.go#L377), which sets message ID offsets like we do here.

The current implementation also only supports a single capability, because we only support eth and are compatible with both `eth/66` and `eth/67`. We should be implementing [message id multiplexing from the devp2p spec](https://github.com/ethereum/devp2p/blob/master/rlpx.md#message-id-based-multiplexing)

**Comment by akirillo** [comment]
> The current implementation of p2p streams only supports a single capability, because we only support eth and are compatible with both eth/66 and eth/67. We should be implementing [message id multiplexing from the devp2p spec](https://github.com/ethereum/devp2p/blob/master/rlpx.md#message-id-based-multiplexing)

Can open an issue for this 👍

**Comment by akirillo** [comment]
^ ref #791
