### ISSUE TITLE
Docs bug `TransactionsManager` and related misleading field

### ISSUE THREAD

**Issue by emhane** [paradigmxyz/reth#6735]
### Describe the feature

Docs bug

https://github.com/paradigmxyz/reth/blob/ca98261d43d40cb2332567fac2bb944fe38e9131/crates/net/network/src/transactions/mod.rs#L226-L227

Also improve naming to better match actual flow, `pending_transactions` (above) is incorrect in context of `TransactionsManager`. This is a stream of transactions that have been successfully inserted into the pool. They are pending in the context of the `TransactionsPool`, but in the context of `TransactionsManager` they are not. `TransactionsManager` is done with those transactions when notice is received that they have been successfully inserted into the pool and thereby are propagated by `TransactionsManager` (insertion into pool means they have passed validation). A better name is `inserted_transactions` or `txns_inserted_into_pool` or `pool_insertions`.

Same goes for `pending_pool_imports`, which is better off being named `pending_pool_insertions` since the code that the `PoolImportFuture` contains is

https://github.com/paradigmxyz/reth/blob/ca98261d43d40cb2332567fac2bb944fe38e9131/crates/net/network/src/transactions/mod.rs#L981

which ends up here

https://github.com/paradigmxyz/reth/blob/ca98261d43d40cb2332567fac2bb944fe38e9131/crates/transaction-pool/src/pool/mod.rs#L385-L393

a function that, for the successful case, ends with the code

https://github.com/paradigmxyz/reth/blob/ca98261d43d40cb2332567fac2bb944fe38e9131/crates/transaction-pool/src/pool/mod.rs#L440-L455

which notifies about a successful pool insertion, not a successful pool import. Hence, `pending_pool_insertions` is a far more correct and therefore helpful name.

Same goes for the `PoolImportFuture`. Other code in `TransactionsManager` referring to `import` should be revised to check if it better be replaced with `insert`.

**Comment by AbnerZheng** [comment]
Can I give it a try?

**Comment by emhane** [comment]
> @emhane What's the difference between `pool insertion` and `pool import`? I found the document for these two functions use `imports transactions` as well.
> 
the tx pool has several stages, so when a tx leaves the tx manager, it becomes pending in the pool.

> https://github.com/paradigmxyz/reth/blob/123b95aeccb6f41b29a9b3249f108cf714d31bd4/crates/transaction-pool/src/traits.rs#L52-L71

 those docs should be updated too, to reflect what the code actually does, so something like
 
 ```rust
Inserts all _external_ transactions into pool and queues for import.
 ```
 
And, see, your question perfectly captures the problematic here, developers have a tendency to trust docs (and log messages). So it's very important they directly reflect the code.

**Comment by AbnerZheng** [comment]
It appears that `import transactions` refers to the synchronization of finalized transactions from other peers. Is that correct?

**Comment by mattsse** [comment]
> Also improve naming to better match actual flow, pending_transactions (above) is incorrect in context of TransactionsManager. This is a stream of transactions that have been successfully inserted into the pool. 

This is not accurate, the `TransactionsManager` is only interested in pending txs, which is a small subset of transactions inserted into the pool:

https://github.com/paradigmxyz/reth/blob/9f91c6ad94f94b2ff1a988c932c9ef0772c5bcc1/crates/net/network/src/transactions/mod.rs#L252-L254

https://github.com/paradigmxyz/reth/blob/9f91c6ad94f94b2ff1a988c932c9ef0772c5bcc1/crates/transaction-pool/src/pool/mod.rs#L146-L146

https://github.com/paradigmxyz/reth/blob/9f91c6ad94f94b2ff1a988c932c9ef0772c5bcc1/crates/transaction-pool/src/pool/mod.rs#L440-L443

https://github.com/paradigmxyz/reth/blob/9f91c6ad94f94b2ff1a988c932c9ef0772c5bcc1/crates/transaction-pool/src/pool/mod.rs#L519-L520

https://github.com/paradigmxyz/reth/blob/9f91c6ad94f94b2ff1a988c932c9ef0772c5bcc1/crates/transaction-pool/src/pool/mod.rs#L37-L40

__pending__ is the proper name here, because we only want to send transactions that are executable at the current state
