### ISSUE TITLE
Accept raw enode in admin namespace for add/remove peers

### ISSUE THREAD

**Issue by mattsse** [paradigmxyz/reth#7003]
### Describe the feature

currently we require a `NodeRecord`:

https://github.com/paradigmxyz/reth/blob/422b8f8e75d80e7f311f1f4812851c33131e1b82/crates/rpc/rpc-api/src/admin.rs#L19-L21

that fails serialization if address info is missing:

https://github.com/paradigmxyz/reth/blob/422b8f8e75d80e7f311f1f4812851c33131e1b82/crates/rpc/rpc-types/src/net.rs#L146-L148

geth supports raw enodes:

https://github.com/ethereum/go-ethereum/blob/b590cae89232299d54aac8aada88c66d00c5b34c/node/api.go#L95-L95

where IP info is optional

missing would break our peer model that requires an address:

https://github.com/paradigmxyz/reth/blob/422b8f8e75d80e7f311f1f4812851c33131e1b82/crates/net/network/src/peers/manager.rs#L904-L908

we can however solve this in several ways:
a) make addr optional
b) add an additional marker and use loopback address

a) seems more appropriate

## TODO
* accept string input in admin rpc functions
* parse enode, add API functions for enode (`Enr`): https://github.com/paradigmxyz/reth/blob/422b8f8e75d80e7f311f1f4812851c33131e1b82/crates/net/network-api/src/lib.rs#L78-L79

not for this issues, but perhaps we should consider storing the raw Enr values, even though we don't need additional fields

ref #7001

**Comment by AbnerZheng** [comment]
Can I give it a try?

**Comment by mattsse** [comment]
@AbnerZheng just checking in, do you have the bandwidth to work on this?

**Comment by AbnerZheng** [comment]
Yes, but I think I need some help.
> 1. accept string input in admin rpc functions. 

There are methods in `AdminApi` , like ` fn add_peer(&self, record: NodeRecord) -> RpcResult<bool>`, which accept `string` by `NodeRecord::from_str`. So for accepting string input, which way do you prefer:
1. change the exiting method `fn add_peer(&self, record: NodeRecord) -> RpcResult<bool>` to `fn add_peer(&self, url:String) -> RpcResult<bool>`, which is similar to geth. 
2. extend existing method of `NodeRecord::from_str` to support `enode`. 

> 2. parse enode, add API functions for enode (Enr)

Looks like there are two things, supporting incomplete enode(no ip and port information) and supporting Enr protocol, should I finish both of them?

**Comment by mattsse** [comment]
> fn add_peer(&self, url:String)

this seems fine, and then add additional API function that accept the enr node instead of the NodeRecord

**Comment by emhane** [comment]
this is related to https://github.com/sigp/discv5/blob/04ac0042a345a9edf93b090007e5d31c008261ed/src/service.rs#L1386-L1389

I wouldn't make the socket optional in `NodeRecord`, I would rather make a new type that doesn't have the socket. in sigp/discv5  the distinction is made between
(i) peers with which a session is established and then go into the kbuckets, and
(ii) peers that just have a session.
only peers with contactable enrs (i.e. with a socket on node record), should go into kbuckets, because those are the peers we put into `Neighbours` messages. what should a peer do with a node in a `Neighbours` response that doesn't have a socket on which it can be contacted on? hence, strongly encourage the type safety here to help us separate logic for kbucket peers and trusted peers that I assume we are waiting for a complete node record from? @mattsse

**Comment by mattsse** [comment]
this will be possible via #7155
