### ISSUE TITLE
Add cli-utils crate 

### ISSUE THREAD

**Issue by mattsse** [paradigmxyz/reth#771]
### Describe the feature

cli functionality will expand, so we can start moving utils (what else) to separate crates, to prevent bloat.

@onbjerg imo we should also move all args to a separate crate

## todo

move everything under https://github.com/paradigmxyz/reth/tree/main/bin/reth/src/util

to new crate `crates/cli/utils`

**Comment by Kuly14** [comment]
I can help with this. But to clarify, I should create a new crate inside `crates` that should be called `cli`, and inside `cli` should be a folder called `utils` where I should move everything from https://github.com/paradigmxyz/reth/tree/main/bin/reth/src/util

Then I should add all the necessary dependencies for the `cli` crate inside the `Cargo.toml` and fix all imports into other files inside `bin`, right?

**Comment by mattsse** [comment]
it should look like 

```
crates
 |__cli
    |__utils
       |__Cargo.toml
```

we start with all utils as a whole and can then refine this, for example a standalone mode for all parser utils etc...

**Comment by onbjerg** [comment]
I'm not sure this is really needed to be honest, the amount of functionality in the CLI is going to be pretty limited so I don't think we're going to end up with Foundry compile times

**Comment by Kuly14** [comment]
> Edit: Makes sense to do this early on considering the util commands might grow big

Ok, great, I will get right on it.

**Comment by Kuly14** [comment]
@mattsse In the initial folder: https://github.com/paradigmxyz/reth/tree/main/bin/reth/src/util there is a `mod.rs` that can't be declared inside the new `lib.rs` in `crates/cli/utils/` like this:

```rust
pub mod mod;
```
Since `mod` is a reserved keyword, I wonder if I should rename `mod.rs` to some other name or rename it to `lib.rs,` which would solve it, but in the rest of the crates, `lib.rs` is always just used to declare modules, so I'm not sure how to proceed. Any ideas?

**Comment by Kuly14** [comment]
I also noticed that inside [`chainspec.rs` line 77](https://github.com/paradigmxyz/reth/blob/main/bin/reth/src/util/chainspec.rs#L77 ), there is this line:
```rust
 "sepolia" => serde_json::from_str(include_str!("../../res/chainspec/mainnet.json"))?,
```
And instead of `sepolia.json,` it takes `mainnet.json`. I don't know if this is a mistake or on purpose, so I am putting it here in case it is a mistake.

**Comment by Kuly14** [comment]
> nice catch, please open an issue for that!

Will do thanks!
