### ISSUE TITLE
Add helpful text for tx pool flags in `reth --help`

### ISSUE THREAD

**Issue by onbjerg** [paradigmxyz/reth#8060]
The flags `pooled-tx-response-soft-limit` and `--pooled-tx-pack-soft-limit` have Rust-specific help text on them (i.e. docs), they should not show up in the CLI. Instead a helpful explainer of what the flags do should show up

See  https://github.com/paradigmxyz/reth/pull/8056#discussion_r1588241968

**Comment by guha-rahul** [comment]
We have add helpful explainers inside the help params in these functions(https://github.com/paradigmxyz/reth/blob/fa59ec8078b6c388b75b4f971013be451b8ab128/crates/node-core/src/args/network.rs#L92-L101) right?

**Comment by onbjerg** [comment]
Yes although the text in the linked section seems fine, so part of the task would be to figure out why that text does not show up in place of the rustdoc text

**Comment by guha-rahul** [comment]
Can you give me some pointers maybe a command whose help actually shows up in the cli?

**Comment by guha-rahul** [comment]
can u give me some more pointers, maybe a command whose help actually shows?

**Comment by DaniPopes** [comment]
There's 2 texts displayed in clap help: help/about and long_help/long_about. These are both inherited from the doc comments, with the first one being just the first line, and the second "long" version being the full doc comment.

This issue should be fixed by either adding `long_help = None` or moving the `help = "..."` text into the doc comment
