### ISSUE TITLE
Consider peer timeout when selecting peers

### ISSUE THREAD

**Issue by MegaRedHand** [paradigmxyz/reth#826]
### Describe the feature

For this we need to share the timeout between `ActiveSession` and `ActiveSessionHandle`. This can be done using an `Arc<AtomicU64>` ([see this commits](https://github.com/paradigmxyz/reth/pull/789/files/01e30d7e7ec492e35a786f5b82c641f9b115925a..3258f5c5c02e89c3111b8ab91f10634c29858155)). Then, when selecting peers, we should prioritize the ones with a lower timeout value (lower latency).

### Additional context

ref https://github.com/paradigmxyz/reth/pull/789#pullrequestreview-1244425031

**Comment by mattsse** [comment]
we'll propagate an `Arc` clone of this via the `SessionEstablished` event and delegate this to the state so we can use it when selecting peers.

**Comment by gakonst** [comment]
Should we be reusing the `Reputation` here? And make our get next peers logic reputation-aware?

**Comment by mattsse** [comment]
not really, because the main purpose for Reputation is to decide to which peer to connect to and when to disconnect, once connected there's no real use for it because the assumption here is that all connected peers are good until disconnected.
Instead for this issue we need to find the best connected peers (for requests) and RTT is a good metric here.
