### ISSUE TITLE
Add dedicated StorageWriter type 

### ISSUE THREAD

**Issue by mattsse** [paradigmxyz/reth#9040]
### Describe the feature

this supersedes #8513 and is intended to provide a simpler to the problem described there.

due to the table style database model, reading and writing to disk isn't as straight forward as supporting codecs because you might want to store certain things in certain tables.

To make this customizable we should introduce a dedicated type that knows how to write things to storage.

so instead of implementing it on the target type like with trieupdates

https://github.com/paradigmxyz/reth/blob/97de9d27bc6a928a72d7bb89413d3b36ed4aae79/crates/trie/trie/src/updates.rs#L132-L132

we will make the type an argument:

```rust
struct StorageWriter {

fn write_trie_updates(TrieUpdates)

}

```

this type should be added to the providers crate for now.
with #8721 all of this will be made generic and converted to a trait.

## TODO
* replace existing native trieupdates function with a struct and make trieupdates an arg

similar thing can be done with execution outcome after:

https://github.com/paradigmxyz/reth/blob/97de9d27bc6a928a72d7bb89413d3b36ed4aae79/crates/storage/provider/src/bundle_state/bundle_state_with_receipts.rs#L12-L12

**Comment by rohankumar17** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/reth).

### My background and how it can be leveraged
I am a second-year Software Engineering student with experience in programming languages such as Python, C, and C++. I have completed internships where I applied my skills in these languages. Recently, I have begun learning Rust and have engaged in practical exercises to enhance my proficiency. I am now seeking real-world issues and projects to work on that will motivate me to further develop my Rust skills and put my knowledge into practice.

### How I plan on tackling this issue
To enhance how TrieUpdates are written to the database, I can introduce a new type called StorageWriter. This involves creating a StorageWriter struct that holds a reference to the transaction (DbTxMut) for accessing the database. The struct will have a write_trie_updates method that iterates through the TrieUpdates, using the existing logic from TrieUpdates::flush for each operation based on the TrieKey and TrieOp. Instead of directly accessing cursors, StorageWriter will have functions like get_account_trie_cursor and get_storage_trie_cursor, which use self.tx to obtain the necessary cursors. The existing write_trie_updates function will be updated to accept a StorageWriter argument and call its write_trie_updates method to handle the actual writing. This approach separates the storage logic from TrieUpdates itself, providing more flexibility for future changes, such as using different storage backends.

**Comment by Rjected** [comment]
> Does this still need work?

no, we have actually completed this already, thanks for the bump!
