### ISSUE TITLE
Prevent direct followup requests to a peer if a response is likely bad

### ISSUE THREAD

**Issue by mattsse** [paradigmxyz/reth#919]
### Describe the feature

currently the `StateFetcher` returns an `Ok` response back to the downloader:

https://github.com/paradigmxyz/reth/blob/115e623ae630b3c1841841dfe192a8cc63505786/crates/net/network/src/fetch/mod.rs#L216-L243

and the downloader can then report the peer if the response is bad.

at this point, the peer is still eligible for a followup request, but depending on the response we can already derive if this was a bad response, for example if 
* empty headers response, but requested more

In this case we should still send it to the downloader but not send a follow-up request since it is likely that this was a bad response.

**Comment by leruaa** [comment]
I would like to take this on

**Comment by leruaa** [comment]
@mattsse I need clarifications on this: As far as I understood, if `res` is `Err(RequestError::BadResponse)`, the method returns `BlockResponseOutcome::BadResponse` so no follow-up request is returned? I must miss something, because I don't get what need to be done.

Also the line where the response is sent back to the downloader is this one, right?
https://github.com/paradigmxyz/reth/blob/115e623ae630b3c1841841dfe192a8cc63505786/crates/net/network/src/fetch/mod.rs#L224

**Comment by mattsse** [comment]
so this is where we send the `Result` back:

https://github.com/paradigmxyz/reth/blob/115e623ae630b3c1841841dfe192a8cc63505786/crates/net/network/src/fetch/mod.rs#L222-L225

and check if it's an `Err` variant via `is_err`

what we want is something like

```rust
fn is_likely_bad_message(&request: HeaderRequest, headers: &[Header]) -> bool; 
```

this should try to determine whether the response was good or bad, more specifically:
if `Ok(Vec<Header>)` matches what we requested in `request`: length check, check first entry.

if the response is likely bad, we don't want to queue in a followup-request immediately.
