### ISSUE TITLE
Sort metrics response

### ISSUE THREAD

**Issue by rkrasiuk** [paradigmxyz/reth#956]
### Describe the feature

Currently, the response from the metrics endpoint comes in an arbitrary order that changes for each request.
The metrics response needs to be sorted.

**Comment by mattsse** [comment]
> Pipe and sort the metrics response

you'd do this via command line `| sort`
unsure if this can be configured via the metrics server

**Comment by mridullpandey** [comment]
Hey i want to work on this please assign to me...

**Comment by rkrasiuk** [comment]
@mattsse would be nice to have it built-in.
@mridullpandey sure, assigning the issue to you

**Comment by onbjerg** [comment]
This is because of https://docs.rs/metrics-exporter-prometheus/latest/src/metrics_exporter_prometheus/recorder.rs.html#28 and https://docs.rs/metrics-exporter-prometheus/latest/src/metrics_exporter_prometheus/recorder.rs.html#101 - there is no real nice way to solve this without solving it upstream, which I would recommend doing.

**Comment by rkrasiuk** [comment]
closing this as not planned
