### ISSUE TITLE
Add AccessList result type to eth_createAccessList

### ISSUE THREAD

**Issue by mattsse** [paradigmxyz/reth#9746]
### Describe the feature

eth_createAccesslist returns a special result type

https://github.com/ethereum/go-ethereum/blob/380688c636a654becc8f114438c2a5d93d2db032/internal/ethapi/api.go#L1475-L1482

where the error is optional and is the evm error

https://github.com/ethereum/go-ethereum/blob/380688c636a654becc8f114438c2a5d93d2db032/internal/ethapi/api.go#L1491-L1498

**Comment by c0np4nn4** [comment]
Hello @mattsse,

From what I understand, the current handling of `eth_createAccessList` is in [rpc-eth-api/src/core.rs](https://github.com/paradigmxyz/reth/blob/6ce7c9e3a38c5757ce14a5c49a22ba0d82e4abbc/crates/rpc/rpc-eth-api/src/core.rs#L593-L603) in the `create_access_list` function, which appears to use `AccessListWithGasUsed` from alloy_eip2930.

The goal of this issue seems to be to replace `AccessListWithGasUsed` with a Rust implementation that performs the same functionality as the one referenced in [geth](https://github.com/ethereum/go-ethereum/blob/380688c636a654becc8f114438c2a5d93d2db032/internal/ethapi/api.go#L1475-L1482), is that correct?

If so, can I take this one?

I'm thinking of implementing it under `rpc-types/src`.

**Comment by mattsse** [comment]
hey @c0np4nn4 

yeah this rpc response returns this object even if the transaction reverted if it didn't the error field is simply ignored, but this makes sure that there's an `"error":` field in the response object
